/*
 * Codegen for i18n.
 *
 * Two outputs in src/locales/_built.ts:
 *
 *   DICTS    — flat key→string per locale, from top-level YAML files
 *              (locales/<lang>/<ns>.yaml). Powers t(key) UI lookups.
 *
 *   CONTENT  — nested object per locale for rich content, from YAML
 *              files in subdirs (locales/<lang>/content/<type>/<slug>.yaml).
 *              Powers getReleaseContent(loc, slug) / getDocContent.
 *              We DON'T flatten body text into the dict — it stays as
 *              structured objects with `title`, `tldr`, `sections[]`.
 *
 * Run by: bun run i18n:build  (auto in dev / build / test scripts).
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs'
import { join, dirname, basename, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import * as yaml from 'js-yaml'

const __dirname = dirname(fileURLToPath(import.meta.url))
const LOCALES_DIR = join(__dirname, '..', 'src', 'locales')
const OUT = join(LOCALES_DIR, '_built.ts')

type Loc = 'es' | 'en' | 'de' | 'ru' | 'gn'
const LOCALES: ReadonlyArray<Loc> = ['es', 'en', 'de', 'ru', 'gn']

const flatten = (prefix: string, obj: Record<string, unknown>, out: Record<string, string>): void => {
  for (const [k, v] of Object.entries(obj)) {
    const key = prefix ? `${prefix}.${k}` : k
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      flatten(key, v as Record<string, unknown>, out)
    } else if (typeof v === 'string') {
      out[key] = v
    } else if (typeof v === 'number' || typeof v === 'boolean') {
      out[key] = String(v)
    }
  }
}

const buildDict = (loc: Loc): Record<string, string> => {
  const dir = join(LOCALES_DIR, loc)
  const out: Record<string, string> = {}
  let files: string[] = []
  try { files = readdirSync(dir).filter((f) => f.endsWith('.yaml')) } catch { return out }
  for (const file of files) {
    const raw = readFileSync(join(dir, file), 'utf8')
    const parsed = yaml.load(raw) as Record<string, unknown> | null
    if (!parsed || typeof parsed !== 'object') continue
    flatten('', parsed, out)
  }
  return out
}

const buildContent = (loc: Loc): Record<string, Record<string, unknown>> => {
  // Walks locales/<lang>/content/<type>/<slug>.yaml and builds:
  //   { [type]: { [slug]: parsed-yaml } }
  const root = join(LOCALES_DIR, loc, 'content')
  const out: Record<string, Record<string, unknown>> = {}
  let types: string[] = []
  try { types = readdirSync(root).filter((d) => {
    try { return statSync(join(root, d)).isDirectory() } catch { return false }
  }) } catch { return out }
  for (const type of types) {
    out[type] = {}
    const typeDir = join(root, type)
    let files: string[] = []
    try { files = readdirSync(typeDir).filter((f) => f.endsWith('.yaml')) } catch { continue }
    for (const file of files) {
      const slug = basename(file, '.yaml')
      const raw = readFileSync(join(typeDir, file), 'utf8')
      const parsed = yaml.load(raw)
      out[type][slug] = parsed
    }
  }
  return out
}

const dicts: Record<Loc, Record<string, string>> = {} as Record<Loc, Record<string, string>>
const content: Record<Loc, Record<string, Record<string, unknown>>> = {} as Record<Loc, Record<string, Record<string, unknown>>>
for (const loc of LOCALES) {
  dicts[loc] = buildDict(loc)
  content[loc] = buildContent(loc)
}

const header = `// AUTOGENERATED — do not edit. Run \`bun run i18n:build\` or any build/test.
// Sources:
//   - flat dict: apps/site/src/locales/<lang>/<ns>.yaml
//   - rich content: apps/site/src/locales/<lang>/content/<type>/<slug>.yaml
`

writeFileSync(OUT, `${header}export const DICTS = ${JSON.stringify(dicts, null, 2)} as const
export const CONTENT = ${JSON.stringify(content, null, 2)} as const
`)

const dictTotals = LOCALES.map((l) => `${l}: ${Object.keys(dicts[l]).length}`).join(', ')
const contentTotals = LOCALES.map((l) => {
  const types = Object.keys(content[l])
  const counts = types.map((t) => `${t}=${Object.keys(content[l][t]).length}`)
  return counts.length ? `${l}: { ${counts.join(', ')} }` : `${l}: 0`
}).join(' | ')
console.log(`built _built.ts`)
console.log(`  DICT keys     { ${dictTotals} }`)
console.log(`  CONTENT slugs ${contentTotals}`)
