/*
 * Reads apps/site/src/locales/<lang>/<ns>.yaml and emits
 * apps/site/src/locales/_built.ts — a plain TS module that the runtime
 * (i18n.ts) imports. Avoids depending on Vite-only `import.meta.glob`
 * so tests (bun test) AND build (Astro/Vite) work identically.
 *
 * Run automatically via prebuild + pretest in package.json.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import * as yaml from 'js-yaml'

const __dirname = dirname(fileURLToPath(import.meta.url))
const LOCALES_DIR = join(__dirname, '..', 'src', 'locales')
const OUT = join(LOCALES_DIR, '_built.ts')

type Loc = 'es' | 'en' | 'de' | 'ru' | 'gn'
const LOCALES: ReadonlyArray<Loc> = ['es', 'en', 'de', 'ru', 'gn']

const flatten = (prefix: string, obj: Record<string, unknown>, out: Record<string, string>): void => {
  for (const [k, v] of Object.entries(obj)) {
    const key = prefix ? `${prefix}.${k}` : k
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      flatten(key, v as Record<string, unknown>, out)
    } else if (typeof v === 'string') {
      out[key] = v
    } else if (typeof v === 'number' || typeof v === 'boolean') {
      out[key] = String(v)
    }
  }
}

const buildLocaleDict = (loc: Loc): Record<string, string> => {
  const dir = join(LOCALES_DIR, loc)
  const out: Record<string, string> = {}
  let files: string[] = []
  try { files = readdirSync(dir).filter((f) => f.endsWith('.yaml')) } catch { return out }
  for (const file of files) {
    const raw = readFileSync(join(dir, file), 'utf8')
    const parsed = yaml.load(raw) as Record<string, unknown> | null
    if (!parsed || typeof parsed !== 'object') continue
    flatten('', parsed, out)
  }
  return out
}

const dicts: Record<Loc, Record<string, string>> = {
  es: buildLocaleDict('es'),
  en: buildLocaleDict('en'),
  de: buildLocaleDict('de'),
  ru: buildLocaleDict('ru'),
  gn: buildLocaleDict('gn'),
}

const json = JSON.stringify(dicts, null, 2)
const header = `// AUTOGENERATED — do not edit. Run \`bun scripts/build-locales.ts\` or build.
// Sources: apps/site/src/locales/<lang>/<ns>.yaml
`
writeFileSync(OUT, `${header}export const DICTS = ${json} as const\n`)

const totals = LOCALES.map((l) => `${l}: ${Object.keys(dicts[l]).length}`).join(', ')
console.log(`built _built.ts — keys per locale: { ${totals} }`)
