// AUTOGENERATED — do not edit. Run `bun run i18n:build` or any build/test.
// Sources:
//   - flat dict: apps/site/src/locales/<lang>/<ns>.yaml
//   - rich content: apps/site/src/locales/<lang>/content/<type>/<slug>.yaml
export const DICTS = {
  "es": {
    "brand.suffix": "PyaServ",
    "brand.tagline_short": "hermano de PyaEats",
    "brand.tagline_long": "construido sobre pya-platform",
    "category.plumbing": "Plomería",
    "category.electrical": "Electricidad",
    "category.cleaning": "Limpieza",
    "category.repair": "Reparaciones",
    "category.beauty": "Belleza",
    "category.teaching": "Clases",
    "category.photography": "Fotografía",
    "category.translation": "Traducción",
    "category.events": "Eventos",
    "category.other": "Otro",
    "clients.title": "Pedidos",
    "clients.description": "Pedidos de clientes en Asunción. Si ofrecés el servicio que buscan, escribiles directo.",
    "clients.heading": "Pedidos abiertos",
    "clients.intro": "Clientes que están buscando un profesional ahora. Para responder, iniciá sesión y abrí una conversación.",
    "clients.empty.title": "Sin pedidos por ahora",
    "clients.empty.hint": "Volvé más tarde o cambiá los filtros.",
    "clients.count.one": "pedido abierto",
    "clients.count.many": "pedidos abiertos",
    "clients.card.cta": "Postularme →",
    "common.loading": "Cargando…",
    "common.sending": "Enviando…",
    "common.saving": "Guardando…",
    "common.publishing": "Publicando…",
    "common.verifying": "Verificando…",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.send": "Enviar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.back": "Atrás",
    "common.next": "Siguiente",
    "common.skip": "Saltar",
    "common.finish": "¡Listo!",
    "common.close": "Cerrar",
    "common.missing_id": "Falta el id",
    "common.price_tbd": "A coordinar",
    "common.budget_tbd": "A coordinar",
    "common.now": "ahora",
    "common.no_description": "(sin descripción)",
    "common.brand_suffix": "PyaServ",
    "common.foot_brother": "hermano de PyaEats",
    "common.foot_built_on": "construido sobre pya-platform",
    "common.error_network": "Error de red. Intentá de nuevo.",
    "demo.banner_msg": "MODO DEMO — los cambios no se guardan. Estás viendo la app real con datos ficticios.",
    "demo.banner_exit": "Salir del demo",
    "demo.exit_confirm_title": "Salir del modo demo",
    "demo.exit_confirm_body": "Nada de lo que probaste se guarda. Tu perfil real (si tenés uno) sigue exactamente como lo dejaste.",
    "demo.exit_confirm_yes": "Sí, salir",
    "demo.exit_confirm_no": "Seguir en demo",
    "demo.demo_tag": "Demo",
    "demo.tour_t1_step1_title": "Empezamos por tu cara",
    "demo.tour_t1_step1_body": "Una buena foto duplica las consultas. Sacate una con luz natural.",
    "demo.tour_t1_step2_title": "Tu headline",
    "demo.tour_t1_step2_body": "Una línea corta: oficio + zona + ventaja. Ej: \"Plomero 24h en Villa Morra\".",
    "demo.tour_t1_step3_title": "Contales quién sos",
    "demo.tour_t1_step3_body": "2-3 frases. Tu experiencia, herramientas, qué zonas cubrís.",
    "demo.tour_t1_step4_title": "Tu teléfono",
    "demo.tour_t1_step4_body": "Cómo te contactan. Usá el mismo que tu WhatsApp si es posible.",
    "demo.tour_t1_step5_title": "WhatsApp",
    "demo.tour_t1_step5_body": "El botón principal de tu perfil llevará acá. Asegurate de que esté actualizado.",
    "demo.tour_t1_step6_title": "Tu barrio principal",
    "demo.tour_t1_step6_body": "Donde tenés más trabajo. Después podés agregar más zonas en la edición avanzada.",
    "demo.tour_t1_step7_title": "¡Listo!",
    "demo.tour_t1_step7_body": "Cada paso adicional sube tu visibilidad. ¡A 100% desbloqueás 7 días de Boost gratis y la insignia \"Perfil Maestro\"!",
    "docs.page_title": "Documentación",
    "docs.page_intro": "Wiki de PyaServ. Cada feature tiene su sección con detalles, link a demo y a producción.",
    "docs.sidebar_aria": "Secciones de documentación",
    "docs.sidebar_search_placeholder": "Buscar…",
    "docs.status_live": "En vivo",
    "docs.status_demo": "Demo",
    "docs.status_soon": "Próximo",
    "docs.status_planned": "Planeado",
    "docs.btn_try_demo": "Probar demo →",
    "docs.btn_view_real": "Ver real →",
    "docs.btn_more": "Más detalles →",
    "docs.btn_soon": "Próximamente",
    "docs.back_to_index": "← Toda la documentación",
    "docs.breadcrumb_root": "Docs",
    "docs.group_profile": "Perfil y visibilidad",
    "docs.group_gamification": "Gamification",
    "docs.group_tools": "Herramientas",
    "docs.group_system": "Sistema",
    "docs.group_roadmap": "Roadmap",
    "docs.group_dev": "Desarrollo",
    "error.network": "Error de red. Intentá de nuevo.",
    "foot.brother": "hermano de PyaEats",
    "foot.built_on": "construido sobre pya-platform",
    "home.title": "Servicios en Paraguay sin comisiones",
    "home.description": "PyaServ conecta profesionales con clientes en Paraguay. Sin comisiones por contacto, sin pagos en plataforma.",
    "home.hero.title": "Servicios en Paraguay, sin intermediarios.",
    "home.hero.body": "Si ofrecés un servicio o si buscás a alguien que resuelva algo concreto, PyaServ tiene un lado para vos. Nada de comisiones por presentar — el trato lo cierran ustedes.",
    "home.specialists.title": "Necesito a un profesional",
    "home.specialists.desc": "Plomeros, electricistas, profes, peluqueras — buscá por barrio y categoría. Contactá directo cuando te decidas.",
    "home.specialists.cta": "Ver profesionales →",
    "home.clients.title": "Ofrezco un servicio",
    "home.clients.desc": "Mirá los pedidos abiertos en tu zona. Si encaja con lo tuyo, escribiles directo — sin filtros, sin pago para postularte.",
    "home.clients.cta": "Ver pedidos →",
    "home.banner.html": "<strong>Estado:</strong> MVP en vivo. Crearás tu perfil de profesional o tu pedido en el panel <a data-banner-link>Mi panel</a>. Si todavía no tenés cuenta, te creamos una con tu email — sin contraseñas.",
    "home.banner.status_label": "Estado:",
    "home.banner.body": "MVP en vivo. Crearás tu perfil de profesional o tu pedido en el panel",
    "home.banner.cta": "Mi panel",
    "home.banner.tail": "Si todavía no tenés cuenta, te creamos una con tu email — sin contraseñas.",
    "home.stats": "<strong>{specs}</strong> profesionales activos · <strong>{reqs}</strong> pedidos abiertos",
    "inquiry.detail.title": "Conversación",
    "inquiry.detail.back": "← Conversaciones",
    "inquiry.detail.heading": "Conversación",
    "inquiry.detail.view_subject": "Ver publicación",
    "inquiry.detail.placeholder": "Escribí un mensaje…",
    "inquiry.detail.about_listing": "Sobre un servicio",
    "inquiry.detail.about_request": "Sobre un pedido",
    "inquiry.back": "← Conversaciones",
    "inquiry.view_subject": "Ver publicación",
    "inquiry.compose_placeholder": "Escribí un mensaje…",
    "inquiry.subject_listing": "Sobre un servicio",
    "inquiry.subject_request": "Sobre un pedido",
    "inquiry.status_negotiating": "Negociando",
    "inquiry.status_in_progress": "En curso",
    "inquiry.status_done": "Terminado",
    "inquiry.status_cancelled": "Cancelado",
    "inquiry.btn_start": "Comenzar trabajo",
    "inquiry.btn_done": "Marcar terminado",
    "inquiry.btn_cancel": "Cancelar",
    "inquiry.cancel_confirm": "¿Cancelar trabajo?",
    "inquiry.review_h": "Calificar trabajo",
    "inquiry.review_body_label": "Comentario (opcional)",
    "inquiry.review_body_placeholder": "Contale a otros cómo fue.",
    "inquiry.review_submit": "Enviar reseña",
    "inquiry.review_thanks": "¡Gracias por tu reseña!",
    "listing.new.title": "Nuevo servicio",
    "listing.new.back": "← Mis servicios",
    "listing.new.intro": "Publicá un servicio concreto que ofrecés. Aparecerá en el catálogo público de profesionales filtrable por categoría.",
    "listing.new.submit": "Publicar",
    "listing.field.category": "Categoría",
    "listing.field.title.placeholder": "Reparación de calefones",
    "listing.field.description.placeholder": "Qué incluye el servicio, qué materiales, en qué zonas…",
    "listing.field.price_from.short": "Precio desde (Gs)",
    "listing.field.unit.none": "—",
    "listing.field.unit.hour": "Hora",
    "listing.field.unit.job": "Trabajo",
    "listing.edit.title": "Editar servicio",
    "listing.edit.not_found": "Servicio no encontrado o no es tuyo",
    "listing.edit.confirm_delete": "¿Eliminar definitivamente?",
    "login.title": "Iniciar sesión",
    "login.description": "Entrá a PyaServ con tu email — sin contraseña. Código de 6 dígitos por correo.",
    "login.intro": "Sin contraseñas — te mandamos un código de 6 dígitos por email.",
    "login.email.placeholder": "tunombre@correo.com",
    "login.send_code": "Enviar código",
    "login.code": "Código (6 dígitos)",
    "login.confirm": "Confirmar",
    "login.change_email": "Cambiar email",
    "login.sent_ok": "Revisá tu email — buscá un código de 6 dígitos.",
    "login.success": "✓ Listo, redirigiendo…",
    "me.title": "Mi panel",
    "me.heading": "Mi panel",
    "me.logout": "Cerrar sesión",
    "me.tabs.aria": "Secciones",
    "me.tabs.profile": "👤 Mi perfil",
    "me.tabs.listings": "🛠️ Mis servicios",
    "me.tabs.requests": "📢 Mis pedidos",
    "me.tabs.inquiries": "💬 Conversaciones",
    "me.tabs.stats": "📊 Estadísticas",
    "me.stats.h": "Estadísticas",
    "me.stats.intro": "Métricas de tu perfil — últimos 30 días.",
    "me.stats.empty": "Aún no tenés perfil de profesional. Creá tu perfil para empezar a ver métricas.",
    "me.stats.profile_view": "Vistas de perfil",
    "me.stats.phone_click": "Clics en teléfono",
    "me.stats.whatsapp_click": "Clics en WhatsApp",
    "me.stats.inquiries": "Consultas recibidas",
    "me.stats.completed": "Trabajos completados",
    "me.session_prefix": "Sesión iniciada · userId",
    "me.profile.h": "Perfil de profesional",
    "me.profile.intro": "Si querés ofrecer servicios, completá tu perfil acá.",
    "me.profile.display_name": "Nombre que mostramos",
    "me.profile.headline.placeholder": "Plomero 24h en Asunción",
    "me.profile.phone.placeholder": "+595 981 234567",
    "me.profile.whatsapp.placeholder": "+595 981 234567",
    "me.profile.barrio.placeholder": "Villa Morra",
    "me.profile.bio.placeholder": "Contales tu experiencia, herramientas, zonas que cubrís…",
    "me.profile.saved": "✓ Perfil guardado",
    "me.profile.geoloc.locating": "Buscando ubicación…",
    "me.profile.geoloc.denied": "Acceso a ubicación denegado",
    "me.profile.geoloc.unavailable": "Geolocalización no disponible",
    "me.profile.completeness.empty": "Perfil completo: 0%",
    "me.listings.h": "Mis servicios publicados",
    "me.listings.new": "+ Nuevo",
    "me.listings.empty_profile.title": "Primero creá tu perfil",
    "me.listings.empty_profile.hint": "Completá la pestaña «Mi perfil» antes de publicar.",
    "me.listings.empty.title": "No publicaste servicios todavía",
    "me.listings.empty.hint": "Tocá «+ Nuevo» arriba para empezar.",
    "me.listings.price_from": "desde",
    "me.listings.confirm_delete": "¿Eliminar este servicio?",
    "me.requests.h": "Mis pedidos como cliente",
    "me.requests.new": "+ Nuevo",
    "me.requests.empty.title": "No publicaste pedidos abiertos",
    "me.requests.empty.hint": "Si necesitás algo concreto, tocá «+ Nuevo».",
    "me.requests.status.open": "Abierto",
    "me.requests.status.closed": "Cerrado",
    "me.requests.public_view": "Vista pública →",
    "me.inquiries.h": "Conversaciones",
    "me.inquiries.empty.title": "Sin conversaciones todavía",
    "me.inquiries.empty.hint": "Cuando contactes a alguien o te contacten, aparecerán acá.",
    "me.inquiries.as_client": "Como cliente",
    "me.inquiries.as_specialist": "Como profesional",
    "me.inquiries.about_listing": "Sobre un servicio",
    "me.inquiries.about_request": "Sobre un pedido",
    "me.notifs.h": "Notificaciones",
    "me.notifs.email": "Recibir avisos por email",
    "me.notifs.saved": "✓ Preferencia guardada",
    "media.upload": "Subir foto",
    "media.uploading": "Subiendo…",
    "media.replace": "Cambiar foto",
    "media.remove": "Quitar",
    "media.too_big": "La imagen debe pesar menos de 5 MB.",
    "media.bad_type": "Solo JPG, PNG o WebP.",
    "nav.menu_open": "Abrir menú",
    "nav.primary_aria": "Principal",
    "nav.specialists": "Profesionales",
    "nav.clients": "Pedidos",
    "nav.docs": "Docs",
    "nav.releases": "Novedades",
    "nav.components": "Componentes",
    "nav.me": "Mi panel",
    "nav.login": "Ingresar",
    "nav.logout": "Cerrar sesión",
    "nav.skip": "Saltar al contenido",
    "nav.lang_label": "Idioma",
    "nav.theme_label": "Cambiar tema (claro/oscuro/auto)",
    "nav.lang_es": "ES",
    "nav.lang_en": "EN",
    "nav.lang_de": "DE",
    "nav.lang_ru": "RU",
    "nav.lang_gn": "GN",
    "nav.lang_es_aria": "Cambiar a español",
    "nav.lang_en_aria": "Cambiar a inglés",
    "nav.lang_de_aria": "Auf Deutsch wechseln",
    "nav.lang_ru_aria": "Переключить на русский",
    "nav.lang_gn_aria": "Cambiar a guaraní",
    "releases.page_title": "Novedades",
    "releases.page_intro": "Lo último que va saliendo en PyaServ. Una entrada por release.",
    "releases.rss_link": "RSS feed",
    "releases.back_to_index": "← Todas las novedades",
    "releases.section_new": "Nuevo",
    "releases.section_improved": "Mejorado",
    "releases.section_fixed": "Arreglado",
    "releases.section_next": "Próximamente",
    "releases.read_more": "Leer más →",
    "request.detail.title": "Pedido",
    "request.detail.status.open": "Abierto",
    "request.detail.status.closed": "Cerrado",
    "request.detail.locked.cta": "iniciá sesión",
    "request.detail.reply_btn": "Postularme",
    "request.detail.compose_h": "Postularme",
    "request.detail.compose.label": "Mensaje al cliente",
    "request.detail.compose.placeholder": "Hola, puedo encargarme…",
    "request.detail.description": "Pedido publicado por un cliente. Postulate sin comisión.",
    "request.new.title": "Nuevo pedido",
    "request.new.back": "← Mis pedidos",
    "request.new.intro": "Describí el trabajo que necesitás. Los profesionales relevantes podrán postularse — el contacto ocurre por mensaje privado.",
    "request.new.submit": "Publicar pedido",
    "request.field.category": "Categoría",
    "request.field.title.placeholder": "Necesito plomero urgente",
    "request.field.description.placeholder": "Qué hay que hacer, fecha aproximada, urgencia, particularidades…",
    "request.field.barrio.placeholder": "Villa Morra",
    "request.field.budget.short": "Presupuesto (Gs)",
    "request.field.status.open": "Abierto",
    "request.field.status.closed": "Cerrado",
    "request.edit.title": "Editar pedido",
    "reviews.h": "Reseñas",
    "reviews.empty": "Sin reseñas todavía.",
    "reviews.avg_one": "reseña",
    "reviews.avg_many": "reseñas",
    "specialist.detail.title": "Perfil",
    "specialist.detail.locked.cta": "iniciá sesión",
    "specialist.detail.verified": "✓ Verificado",
    "specialist.detail.contact_btn": "Enviar mensaje",
    "specialist.detail.services_h": "Servicios que ofrece",
    "specialist.detail.no_services.title": "Aún no publicó servicios",
    "specialist.detail.compose_h": "Escribirle",
    "specialist.detail.compose.label": "Mensaje",
    "specialist.detail.compose.placeholder": "Hola, me interesa…",
    "specialist.detail.no_listings_err": "Este profesional aún no publicó servicios; no se puede iniciar la conversación todavía.",
    "specialist.detail.price_from": "desde",
    "specialist.detail.per_hour": "hora",
    "specialist.detail.per_job": "trabajo",
    "specialist.detail.price_tbd": "Precio a coordinar",
    "specialist.detail.ask_about": "Consultar sobre este servicio",
    "specialist.detail.description": "Perfil del profesional en PyaServ. Contactá directo sin comisiones.",
    "specialists.title": "Profesionales",
    "specialists.description": "Plomeros, electricistas, peluqueras, profes — encontralos en tu barrio en Asunción.",
    "specialists.heading": "Profesionales disponibles",
    "specialists.intro": "Filtrá por categoría o barrio. El contacto se hace fuera de la plataforma; PyaServ solo presenta.",
    "specialists.filter.category.all": "Todas",
    "specialists.filter.barrio.placeholder": "Villa Morra, Carmelitas…",
    "specialists.filter.near_me": "📍 Cerca de mí",
    "specialists.filter.near_me_on": "📍 Cerca de mí · activado",
    "specialists.filter.near_me_denied": "Sin acceso a ubicación",
    "specialists.empty.title": "Nada por acá",
    "specialists.empty.hint": "Probá quitar filtros o cambiar el barrio.",
    "specialists.count.one": "profesional",
    "specialists.count.many": "profesionales",
    "specialists.card.verified": "✓ verificado",
    "specialists.card.cta": "Ver perfil →",
    "time.now": "ahora",
    "time.min_ago": "hace {n} min",
    "time.hour_ago": "hace {n} h",
    "time.day_ago": "hace {n} d"
  },
  "en": {
    "brand.suffix": "PyaServ",
    "brand.tagline_short": "sibling of PyaEats",
    "brand.tagline_long": "built on pya-platform",
    "category.plumbing": "Plumbing",
    "category.electrical": "Electrical",
    "category.cleaning": "Cleaning",
    "category.repair": "Repairs",
    "category.beauty": "Beauty",
    "category.teaching": "Lessons",
    "category.photography": "Photography",
    "category.translation": "Translation",
    "category.events": "Events",
    "category.other": "Other",
    "clients.title": "Requests",
    "clients.description": "Client requests in Asunción. If you offer the service they need, message them directly.",
    "clients.heading": "Open requests",
    "clients.intro": "Clients looking for a specialist right now. To reply, sign in and start a conversation.",
    "clients.empty.title": "No requests right now",
    "clients.empty.hint": "Check back later or change the filters.",
    "clients.count.one": "open request",
    "clients.count.many": "open requests",
    "clients.card.cta": "Apply →",
    "common.loading": "Loading…",
    "common.sending": "Sending…",
    "common.saving": "Saving…",
    "common.publishing": "Publishing…",
    "common.verifying": "Verifying…",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.send": "Send",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.back": "Back",
    "common.next": "Next",
    "common.skip": "Skip",
    "common.finish": "Done!",
    "common.close": "Close",
    "common.missing_id": "Missing id",
    "common.price_tbd": "To be agreed",
    "common.budget_tbd": "To be agreed",
    "common.now": "now",
    "common.no_description": "(no description)",
    "common.brand_suffix": "PyaServ",
    "common.foot_brother": "sibling of PyaEats",
    "common.foot_built_on": "built on pya-platform",
    "common.error_network": "Network error. Please try again.",
    "demo.banner_msg": "DEMO MODE — changes are not saved. You are viewing the real app with fake data.",
    "demo.banner_exit": "Exit demo",
    "demo.exit_confirm_title": "Exit demo mode",
    "demo.exit_confirm_body": "Nothing you tried is saved. Your real profile (if any) is exactly as you left it.",
    "demo.exit_confirm_yes": "Yes, exit",
    "demo.exit_confirm_no": "Stay in demo",
    "demo.demo_tag": "Demo",
    "demo.tour_t1_step1_title": "Start with your face",
    "demo.tour_t1_step1_body": "A good photo doubles inquiries. Take one in natural light.",
    "demo.tour_t1_step2_title": "Your headline",
    "demo.tour_t1_step2_body": "One short line: trade + area + edge. Eg: \"24h plumber in Villa Morra\".",
    "demo.tour_t1_step3_title": "Tell who you are",
    "demo.tour_t1_step3_body": "2-3 sentences. Your experience, tools, areas you cover.",
    "demo.tour_t1_step4_title": "Your phone",
    "demo.tour_t1_step4_body": "How clients reach you. Use the same one as WhatsApp if possible.",
    "demo.tour_t1_step5_title": "WhatsApp",
    "demo.tour_t1_step5_body": "The main button on your profile goes here. Keep it up to date.",
    "demo.tour_t1_step6_title": "Your main neighborhood",
    "demo.tour_t1_step6_body": "Where you have most work. You can add more areas later in advanced edit.",
    "demo.tour_t1_step7_title": "Done!",
    "demo.tour_t1_step7_body": "Each step raises your visibility. At 100% you unlock 7 free Boost days and the \"Master Profile\" badge!",
    "docs.page_title": "Documentation",
    "docs.page_intro": "PyaServ wiki. Each feature has its section with details, demo link, and production link.",
    "docs.sidebar_aria": "Documentation sections",
    "docs.sidebar_search_placeholder": "Search…",
    "docs.status_live": "Live",
    "docs.status_demo": "Demo",
    "docs.status_soon": "Coming",
    "docs.status_planned": "Planned",
    "docs.btn_try_demo": "Try demo →",
    "docs.btn_view_real": "See live →",
    "docs.btn_more": "More details →",
    "docs.btn_soon": "Coming soon",
    "docs.back_to_index": "← All documentation",
    "docs.breadcrumb_root": "Docs",
    "docs.group_profile": "Profile & visibility",
    "docs.group_gamification": "Gamification",
    "docs.group_tools": "Tools",
    "docs.group_system": "System",
    "docs.group_roadmap": "Roadmap",
    "docs.group_dev": "Development",
    "error.network": "Network error. Please try again.",
    "foot.brother": "sibling of PyaEats",
    "foot.built_on": "built on pya-platform",
    "home.title": "Services in Paraguay without fees",
    "home.description": "PyaServ connects specialists with clients across Paraguay. No contact fees, no in-platform payments.",
    "home.hero.title": "Services in Paraguay, no middlemen.",
    "home.hero.body": "Whether you offer a service or you are looking for someone to get something done, PyaServ has a side for you. No fees for introducing — you close the deal directly.",
    "home.specialists.title": "I need a specialist",
    "home.specialists.desc": "Plumbers, electricians, tutors, hairdressers — search by neighborhood and category. Reach out directly when you decide.",
    "home.specialists.cta": "Browse specialists →",
    "home.clients.title": "I offer a service",
    "home.clients.desc": "See open requests in your area. If it matches what you do, message them directly — no filters, no fee to apply.",
    "home.clients.cta": "Browse requests →",
    "home.banner.html": "<strong>Status:</strong> MVP live. Create your specialist profile or your request from the <a data-banner-link>My dashboard</a> panel. If you do not have an account yet, we create one with your email — no passwords.",
    "home.banner.status_label": "Status:",
    "home.banner.body": "MVP live. Create your specialist profile or your request from the",
    "home.banner.cta": "My dashboard",
    "home.banner.tail": "If you do not have an account yet, we create one with your email — no passwords.",
    "home.stats": "<strong>{specs}</strong> active specialists · <strong>{reqs}</strong> open requests",
    "inquiry.detail.title": "Conversation",
    "inquiry.detail.back": "← Conversations",
    "inquiry.detail.heading": "Conversation",
    "inquiry.detail.view_subject": "View post",
    "inquiry.detail.placeholder": "Write a message…",
    "inquiry.detail.about_listing": "About a service",
    "inquiry.detail.about_request": "About a request",
    "inquiry.back": "← Conversations",
    "inquiry.view_subject": "View post",
    "inquiry.compose_placeholder": "Write a message…",
    "inquiry.subject_listing": "About a service",
    "inquiry.subject_request": "About a request",
    "inquiry.status_negotiating": "Negotiating",
    "inquiry.status_in_progress": "In progress",
    "inquiry.status_done": "Done",
    "inquiry.status_cancelled": "Cancelled",
    "inquiry.btn_start": "Start work",
    "inquiry.btn_done": "Mark done",
    "inquiry.btn_cancel": "Cancel",
    "inquiry.cancel_confirm": "Cancel this work?",
    "inquiry.review_h": "Rate the work",
    "inquiry.review_body_label": "Comment (optional)",
    "inquiry.review_body_placeholder": "Tell others how it went.",
    "inquiry.review_submit": "Submit review",
    "inquiry.review_thanks": "Thanks for your review!",
    "listing.new.title": "New service",
    "listing.new.back": "← My services",
    "listing.new.intro": "Publish a concrete service you offer. It will appear in the public catalog of specialists, filterable by category.",
    "listing.new.submit": "Publish",
    "listing.field.category": "Category",
    "listing.field.title.placeholder": "Water heater repair",
    "listing.field.description.placeholder": "What the service includes, materials, areas you cover…",
    "listing.field.price_from.short": "Price from (Gs)",
    "listing.field.unit.none": "—",
    "listing.field.unit.hour": "Hour",
    "listing.field.unit.job": "Job",
    "listing.edit.title": "Edit service",
    "listing.edit.not_found": "Service not found or not yours",
    "listing.edit.confirm_delete": "Delete permanently?",
    "login.title": "Sign in",
    "login.description": "Sign in to PyaServ with your email — no password. 6-digit code by email.",
    "login.intro": "No passwords — we email you a 6-digit code.",
    "login.email.placeholder": "yourname@email.com",
    "login.send_code": "Send code",
    "login.code": "Code (6 digits)",
    "login.confirm": "Confirm",
    "login.change_email": "Change email",
    "login.sent_ok": "Check your email — look for a 6-digit code.",
    "login.success": "✓ Done, redirecting…",
    "me.title": "My dashboard",
    "me.heading": "My dashboard",
    "me.logout": "Sign out",
    "me.tabs.aria": "Sections",
    "me.tabs.profile": "👤 My profile",
    "me.tabs.listings": "🛠️ My services",
    "me.tabs.requests": "📢 My requests",
    "me.tabs.inquiries": "💬 Conversations",
    "me.tabs.stats": "📊 Stats",
    "me.stats.h": "Stats",
    "me.stats.intro": "Profile metrics — last 30 days.",
    "me.stats.empty": "You don't have a specialist profile yet. Create one to start seeing metrics.",
    "me.stats.profile_view": "Profile views",
    "me.stats.phone_click": "Phone clicks",
    "me.stats.whatsapp_click": "WhatsApp clicks",
    "me.stats.inquiries": "Inquiries received",
    "me.stats.completed": "Jobs completed",
    "me.session_prefix": "Signed in · userId",
    "me.profile.h": "Specialist profile",
    "me.profile.intro": "If you want to offer services, fill out your profile here.",
    "me.profile.display_name": "Display name",
    "me.profile.headline.placeholder": "24/7 plumber in Asunción",
    "me.profile.phone.placeholder": "+595 981 234567",
    "me.profile.whatsapp.placeholder": "+595 981 234567",
    "me.profile.barrio.placeholder": "Villa Morra",
    "me.profile.bio.placeholder": "Tell about your experience, tools, areas you cover…",
    "me.profile.saved": "✓ Profile saved",
    "me.profile.geoloc.locating": "Locating…",
    "me.profile.geoloc.denied": "Location access denied",
    "me.profile.geoloc.unavailable": "Geolocation unavailable",
    "me.profile.completeness.empty": "Profile complete: 0%",
    "me.listings.h": "My published services",
    "me.listings.new": "+ New",
    "me.listings.empty_profile.title": "Create your profile first",
    "me.listings.empty_profile.hint": "Fill out the “My profile” tab before publishing.",
    "me.listings.empty.title": "You have not published services yet",
    "me.listings.empty.hint": "Tap “+ New” above to start.",
    "me.listings.price_from": "from",
    "me.listings.confirm_delete": "Delete this service?",
    "me.requests.h": "My requests as a client",
    "me.requests.new": "+ New",
    "me.requests.empty.title": "You have no open requests",
    "me.requests.empty.hint": "If you need something specific, tap “+ New”.",
    "me.requests.status.open": "Open",
    "me.requests.status.closed": "Closed",
    "me.requests.public_view": "Public view →",
    "me.inquiries.h": "Conversations",
    "me.inquiries.empty.title": "No conversations yet",
    "me.inquiries.empty.hint": "When you contact someone or they contact you, threads will appear here.",
    "me.inquiries.as_client": "As client",
    "me.inquiries.as_specialist": "As specialist",
    "me.inquiries.about_listing": "About a service",
    "me.inquiries.about_request": "About a request",
    "me.notifs.h": "Notifications",
    "me.notifs.email": "Receive email notifications",
    "me.notifs.saved": "✓ Preference saved",
    "media.upload": "Upload photo",
    "media.uploading": "Uploading…",
    "media.replace": "Replace photo",
    "media.remove": "Remove",
    "media.too_big": "Image must be under 5 MB.",
    "media.bad_type": "Only JPG, PNG or WebP.",
    "nav.menu_open": "Open menu",
    "nav.primary_aria": "Main",
    "nav.specialists": "Specialists",
    "nav.clients": "Requests",
    "nav.docs": "Docs",
    "nav.releases": "Releases",
    "nav.components": "Components",
    "nav.me": "My dashboard",
    "nav.login": "Sign in",
    "nav.logout": "Sign out",
    "nav.skip": "Skip to content",
    "nav.lang_label": "Language",
    "nav.theme_label": "Toggle theme (light/dark/auto)",
    "nav.lang_es": "ES",
    "nav.lang_en": "EN",
    "nav.lang_de": "DE",
    "nav.lang_ru": "RU",
    "nav.lang_gn": "GN",
    "nav.lang_es_aria": "Switch to Spanish",
    "nav.lang_en_aria": "Switch to English",
    "nav.lang_de_aria": "Switch to German",
    "nav.lang_ru_aria": "Switch to Russian",
    "nav.lang_gn_aria": "Switch to Guarani",
    "releases.page_title": "Releases",
    "releases.page_intro": "What is shipping on PyaServ. One entry per release.",
    "releases.rss_link": "RSS feed",
    "releases.back_to_index": "← All releases",
    "releases.section_new": "New",
    "releases.section_improved": "Improved",
    "releases.section_fixed": "Fixed",
    "releases.section_next": "Coming soon",
    "releases.read_more": "Read more →",
    "request.detail.title": "Request",
    "request.detail.status.open": "Open",
    "request.detail.status.closed": "Closed",
    "request.detail.locked.cta": "sign in",
    "request.detail.reply_btn": "Apply",
    "request.detail.compose_h": "Apply",
    "request.detail.compose.label": "Message to the client",
    "request.detail.compose.placeholder": "Hi, I can take this on…",
    "request.detail.description": "Request posted by a client. Apply directly, no commission.",
    "request.new.title": "New request",
    "request.new.back": "← My requests",
    "request.new.intro": "Describe the work you need. Relevant specialists will be able to apply — contact happens by private message.",
    "request.new.submit": "Publish request",
    "request.field.category": "Category",
    "request.field.title.placeholder": "Need a plumber urgently",
    "request.field.description.placeholder": "What needs to be done, approximate date, urgency, details…",
    "request.field.barrio.placeholder": "Villa Morra",
    "request.field.budget.short": "Budget (Gs)",
    "request.field.status.open": "Open",
    "request.field.status.closed": "Closed",
    "request.edit.title": "Edit request",
    "reviews.h": "Reviews",
    "reviews.empty": "No reviews yet.",
    "reviews.avg_one": "review",
    "reviews.avg_many": "reviews",
    "specialist.detail.title": "Profile",
    "specialist.detail.locked.cta": "sign in",
    "specialist.detail.verified": "✓ Verified",
    "specialist.detail.contact_btn": "Send message",
    "specialist.detail.services_h": "Services offered",
    "specialist.detail.no_services.title": "No services posted yet",
    "specialist.detail.compose_h": "Message",
    "specialist.detail.compose.label": "Message",
    "specialist.detail.compose.placeholder": "Hi, I am interested…",
    "specialist.detail.no_listings_err": "This specialist has not posted services yet; the conversation cannot be started.",
    "specialist.detail.price_from": "from",
    "specialist.detail.per_hour": "hour",
    "specialist.detail.per_job": "job",
    "specialist.detail.price_tbd": "Price to be agreed",
    "specialist.detail.ask_about": "Ask about this service",
    "specialist.detail.description": "Specialist profile on PyaServ. Reach out directly, no commissions.",
    "specialists.title": "Specialists",
    "specialists.description": "Plumbers, electricians, hairdressers, tutors — find them in your neighborhood in Asunción.",
    "specialists.heading": "Available specialists",
    "specialists.intro": "Filter by category or neighborhood. Contact happens outside the platform; PyaServ only introduces.",
    "specialists.filter.category.all": "All",
    "specialists.filter.barrio.placeholder": "Villa Morra, Carmelitas…",
    "specialists.filter.near_me": "📍 Near me",
    "specialists.filter.near_me_on": "📍 Near me · on",
    "specialists.filter.near_me_denied": "Location access denied",
    "specialists.empty.title": "Nothing here",
    "specialists.empty.hint": "Try removing filters or changing the neighborhood.",
    "specialists.count.one": "specialist",
    "specialists.count.many": "specialists",
    "specialists.card.verified": "✓ verified",
    "specialists.card.cta": "View profile →",
    "time.now": "now",
    "time.min_ago": "{n} min ago",
    "time.hour_ago": "{n} h ago",
    "time.day_ago": "{n} d ago"
  },
  "de": {
    "common.loading": "Lädt…",
    "common.sending": "Wird gesendet…",
    "common.saving": "Wird gespeichert…",
    "common.publishing": "Wird veröffentlicht…",
    "common.verifying": "Wird verifiziert…",
    "common.save": "Speichern",
    "common.cancel": "Abbrechen",
    "common.send": "Senden",
    "common.delete": "Löschen",
    "common.edit": "Bearbeiten",
    "common.back": "Zurück",
    "common.next": "Weiter",
    "common.skip": "Überspringen",
    "common.finish": "Fertig!",
    "common.close": "Schließen",
    "common.missing_id": "ID fehlt",
    "common.price_tbd": "Nach Absprache",
    "common.budget_tbd": "Nach Absprache",
    "common.now": "jetzt",
    "common.no_description": "(keine Beschreibung)",
    "common.brand_suffix": "PyaServ",
    "common.foot_brother": "Schwester von PyaEats",
    "common.foot_built_on": "gebaut auf pya-platform",
    "common.error_network": "Netzwerkfehler. Bitte erneut versuchen.",
    "demo.banner_msg": "DEMO-MODUS — Änderungen werden nicht gespeichert. Du siehst die echte App mit fiktiven Daten.",
    "demo.banner_exit": "Demo verlassen",
    "demo.exit_confirm_title": "Demo-Modus verlassen",
    "demo.exit_confirm_body": "Nichts, was du ausprobiert hast, wird gespeichert. Dein echtes Profil (falls vorhanden) bleibt unverändert.",
    "demo.exit_confirm_yes": "Ja, verlassen",
    "demo.exit_confirm_no": "Im Demo bleiben",
    "demo.demo_tag": "Demo",
    "demo.tour_t1_step1_title": "Fangen wir mit deinem Gesicht an",
    "demo.tour_t1_step1_body": "Ein gutes Foto verdoppelt die Anfragen. Mach eins bei natürlichem Licht.",
    "demo.tour_t1_step2_title": "Deine Überschrift",
    "demo.tour_t1_step2_body": "Eine kurze Zeile: Beruf + Gebiet + Vorteil. Z.B.: \"24h Klempner in Villa Morra\".",
    "demo.tour_t1_step3_title": "Wer bist du?",
    "demo.tour_t1_step3_body": "2-3 Sätze. Deine Erfahrung, Werkzeuge, Gebiete die du abdeckst.",
    "demo.tour_t1_step4_title": "Deine Telefonnummer",
    "demo.tour_t1_step4_body": "Wie Kunden dich erreichen. Wenn möglich, dieselbe wie deine WhatsApp-Nummer.",
    "demo.tour_t1_step5_title": "WhatsApp",
    "demo.tour_t1_step5_body": "Der Hauptbutton deines Profils führt hierhin. Halte sie aktuell.",
    "demo.tour_t1_step6_title": "Dein Hauptviertel",
    "demo.tour_t1_step6_body": "Wo du am meisten arbeitest. Weitere Gebiete kannst du später hinzufügen.",
    "demo.tour_t1_step7_title": "Fertig!",
    "demo.tour_t1_step7_body": "Jeder Schritt erhöht deine Sichtbarkeit. Bei 100% schaltest du 7 Tage Boost und das \"Master Profile\"-Abzeichen frei!",
    "docs.page_title": "Dokumentation",
    "docs.page_intro": "PyaServ-Wiki. Jedes Feature hat seinen Abschnitt mit Details, Demo-Link und Produktions-Link.",
    "docs.sidebar_aria": "Dokumentationsabschnitte",
    "docs.sidebar_search_placeholder": "Suchen…",
    "docs.status_live": "Live",
    "docs.status_demo": "Demo",
    "docs.status_soon": "Bald",
    "docs.status_planned": "Geplant",
    "docs.btn_try_demo": "Demo testen →",
    "docs.btn_view_real": "Live ansehen →",
    "docs.btn_more": "Mehr Details →",
    "docs.btn_soon": "Demnächst",
    "docs.back_to_index": "← Gesamte Dokumentation",
    "docs.breadcrumb_root": "Docs",
    "docs.group_profile": "Profil & Sichtbarkeit",
    "docs.group_gamification": "Gamification",
    "docs.group_tools": "Werkzeuge",
    "docs.group_system": "System",
    "docs.group_roadmap": "Roadmap",
    "docs.group_dev": "Entwicklung",
    "nav.menu_open": "Menü öffnen",
    "nav.primary_aria": "Hauptnavigation",
    "nav.specialists": "Fachleute",
    "nav.clients": "Anfragen",
    "nav.docs": "Docs",
    "nav.releases": "Neuigkeiten",
    "nav.components": "Komponenten",
    "nav.me": "Mein Konto",
    "nav.login": "Anmelden",
    "nav.logout": "Abmelden",
    "nav.skip": "Zum Inhalt springen",
    "nav.lang_label": "Sprache",
    "nav.theme_label": "Thema wechseln (hell/dunkel/auto)",
    "nav.lang_es": "ES",
    "nav.lang_en": "EN",
    "nav.lang_de": "DE",
    "nav.lang_ru": "RU",
    "nav.lang_gn": "GN",
    "nav.lang_es_aria": "Auf Spanisch wechseln",
    "nav.lang_en_aria": "Auf Englisch wechseln",
    "nav.lang_de_aria": "Auf Deutsch wechseln",
    "nav.lang_ru_aria": "Auf Russisch wechseln",
    "nav.lang_gn_aria": "Auf Guarani wechseln",
    "releases.page_title": "Neuigkeiten",
    "releases.page_intro": "Was bei PyaServ ausgeliefert wird. Ein Eintrag pro Release.",
    "releases.rss_link": "RSS-Feed",
    "releases.back_to_index": "← Alle Releases",
    "releases.section_new": "Neu",
    "releases.section_improved": "Verbessert",
    "releases.section_fixed": "Behoben",
    "releases.section_next": "Demnächst",
    "releases.read_more": "Weiterlesen →"
  },
  "ru": {
    "common.loading": "Загрузка…",
    "common.sending": "Отправка…",
    "common.saving": "Сохранение…",
    "common.publishing": "Публикация…",
    "common.verifying": "Проверка…",
    "common.save": "Сохранить",
    "common.cancel": "Отмена",
    "common.send": "Отправить",
    "common.delete": "Удалить",
    "common.edit": "Изменить",
    "common.back": "Назад",
    "common.next": "Далее",
    "common.skip": "Пропустить",
    "common.finish": "Готово!",
    "common.close": "Закрыть",
    "common.missing_id": "Не указан ID",
    "common.price_tbd": "По согласованию",
    "common.budget_tbd": "По согласованию",
    "common.now": "сейчас",
    "common.no_description": "(без описания)",
    "common.brand_suffix": "PyaServ",
    "common.foot_brother": "побратим PyaEats",
    "common.foot_built_on": "построен на pya-platform",
    "common.error_network": "Ошибка сети. Попробуйте ещё раз.",
    "demo.banner_msg": "РЕЖИМ ДЕМО — изменения не сохраняются. Вы видите реальное приложение с тестовыми данными.",
    "demo.banner_exit": "Выйти из демо",
    "demo.exit_confirm_title": "Выйти из режима демо",
    "demo.exit_confirm_body": "Ничего из того, что вы попробовали, не сохранится. Ваш реальный профиль (если есть) останется как был.",
    "demo.exit_confirm_yes": "Да, выйти",
    "demo.exit_confirm_no": "Остаться в демо",
    "demo.demo_tag": "Демо",
    "demo.tour_t1_step1_title": "Начнём с фото",
    "demo.tour_t1_step1_body": "Хорошее фото удваивает заявки. Снимите при дневном свете.",
    "demo.tour_t1_step2_title": "Ваш заголовок",
    "demo.tour_t1_step2_body": "Одна короткая строка: профессия + район + преимущество. Напр.: «Сантехник 24/7 в Villa Morra».",
    "demo.tour_t1_step3_title": "Расскажите о себе",
    "demo.tour_t1_step3_body": "2-3 предложения. Ваш опыт, инструменты, районы которые покрываете.",
    "demo.tour_t1_step4_title": "Ваш телефон",
    "demo.tour_t1_step4_body": "Как клиенты связываются. По возможности — тот же что и WhatsApp.",
    "demo.tour_t1_step5_title": "WhatsApp",
    "demo.tour_t1_step5_body": "Главная кнопка профиля ведёт сюда. Держите номер актуальным.",
    "demo.tour_t1_step6_title": "Основной район",
    "demo.tour_t1_step6_body": "Где у вас больше всего работы. Дополнительные районы добавите позже.",
    "demo.tour_t1_step7_title": "Готово!",
    "demo.tour_t1_step7_body": "Каждый шаг повышает вашу видимость. На 100% открываются 7 дней Boost и значок «Master Profile»!",
    "docs.page_title": "Документация",
    "docs.page_intro": "Вики PyaServ. У каждой фичи свой раздел с деталями, ссылкой на демо и продакшен.",
    "docs.sidebar_aria": "Разделы документации",
    "docs.sidebar_search_placeholder": "Поиск…",
    "docs.status_live": "В работе",
    "docs.status_demo": "Демо",
    "docs.status_soon": "Скоро",
    "docs.status_planned": "Запланировано",
    "docs.btn_try_demo": "Попробовать демо →",
    "docs.btn_view_real": "Открыть →",
    "docs.btn_more": "Подробнее →",
    "docs.btn_soon": "Скоро",
    "docs.back_to_index": "← Вся документация",
    "docs.breadcrumb_root": "Docs",
    "docs.group_profile": "Профиль и видимость",
    "docs.group_gamification": "Геймификация",
    "docs.group_tools": "Инструменты",
    "docs.group_system": "Система",
    "docs.group_roadmap": "Дорожная карта",
    "docs.group_dev": "Разработка",
    "nav.menu_open": "Открыть меню",
    "nav.primary_aria": "Главная навигация",
    "nav.specialists": "Специалисты",
    "nav.clients": "Заявки",
    "nav.docs": "Документация",
    "nav.releases": "Обновления",
    "nav.components": "Компоненты",
    "nav.me": "Мой кабинет",
    "nav.login": "Войти",
    "nav.logout": "Выйти",
    "nav.skip": "Перейти к содержимому",
    "nav.lang_label": "Язык",
    "nav.theme_label": "Сменить тему (светлая/тёмная/авто)",
    "nav.lang_es": "ES",
    "nav.lang_en": "EN",
    "nav.lang_de": "DE",
    "nav.lang_ru": "RU",
    "nav.lang_gn": "GN",
    "nav.lang_es_aria": "Переключить на испанский",
    "nav.lang_en_aria": "Переключить на английский",
    "nav.lang_de_aria": "Переключить на немецкий",
    "nav.lang_ru_aria": "Переключить на русский",
    "nav.lang_gn_aria": "Переключить на гуарани",
    "releases.page_title": "Обновления",
    "releases.page_intro": "Что нового в PyaServ. По одной записи на релиз.",
    "releases.rss_link": "RSS-канал",
    "releases.back_to_index": "← Все обновления",
    "releases.section_new": "Новое",
    "releases.section_improved": "Улучшено",
    "releases.section_fixed": "Исправлено",
    "releases.section_next": "Скоро",
    "releases.read_more": "Читать дальше →"
  },
  "gn": {
    "common.save": "Mbohasapyre",
    "common.finish": "I porã!"
  }
} as const
export const CONTENT = {
  "es": {
    "docs": {
      "analitica": {
        "title": "Analítica del perfil",
        "tldr": "Vistas del perfil, clicks a WhatsApp, conversión, tiempo de respuesta, comparación con el promedio del rubro en tu barrio.",
        "sections": [
          {
            "heading": "Métricas (últimos 30 días)",
            "body": "· Profile views\n· Phone clicks\n· WhatsApp clicks\n· Inquiries received\n· Jobs completed\n· Reviews acumuladas + rating promedio"
          },
          {
            "heading": "Próximos sprints",
            "body": "· Sparkline por día\n· Source attribution (Google / WhatsApp share / direct / search en PyaServ)\n· Heatmap hora-de-día\n· Comparación vs avg del rubro en barrio"
          }
        ]
      },
      "cotizador": {
        "title": "Cotizador rápido",
        "tldr": "Plantillas por oficio + editor de items + IVA opcional + PDF descargable + envío por WhatsApp con un click.",
        "sections": [
          {
            "heading": "Flow",
            "body": "1. Elegí plantilla (opcional, por oficio).\n2. Llená/editá items (nombre + cantidad + precio).\n3. Toggle IVA 10 %.\n4. \"Guardar y descargar PDF\" — genera PDF client-side con jsPDF.\n5. \"Enviar por WhatsApp\" — abre wa.me con un mensaje pre-llenado con el resumen."
          },
          {
            "heading": "Plantillas",
            "body": "Sin plantillas pre-cargadas (vacío al inicio). Después de armar tu primer presupuesto, podés \"Guardar como plantilla\" para reutilizar."
          },
          {
            "heading": "PDF",
            "body": "Generado en el browser con jspdf 4.2. Sin server side fonts ni Workers complejos. Funciona offline (una vez que la página esté cacheada)."
          }
        ]
      },
      "demo-mode": {
        "title": "Demo Mode v2",
        "tldr": "Cualquier página real con ?demo=1 = apiFetch interceptado, datos mock, banner permanente, identidad logged-out. Mismo código que producción.",
        "sections": [
          {
            "heading": "Cómo funciona",
            "body": "apiFetch detecta `URLSearchParams.has('demo')` y devuelve canned stubs en vez de hacer fetch real. Todas las páginas reales (`/me/`, `/p/<slug>`, `/me/quotes/new/`) renderizan con los mismos componentes pero con datos demo."
          },
          {
            "heading": "Safety Charter (10 mechanisms)",
            "body": "Spec §15.2. Banner naranja non-dismissible, body tint, html[data-demo-mode], prefijo \"Demo:\" en todos los nombres, sessionStorage state, logged-out identity, exit modal, 10-min idle timeout, NO data import, audit beacon."
          },
          {
            "heading": "Tours dentro de Demo",
            "body": "?demo=1&tour=T1 lanza el tour overlay sobre la página real (IntelliJ-style en v2 próximo)."
          }
        ]
      },
      "filtros-leads": {
        "title": "Filtros de leads",
        "tldr": "Configurá presupuesto mínimo y escondé cuentas nuevas (anti-spam). Hoy persistido en perfil; filtering en query — próximo sprint.",
        "sections": [
          {
            "heading": "Opciones actuales",
            "body": "· `minBudget` (Gs): no mostrar inquiries por debajo de X\n· `hideNewAccounts`: esconder de cuentas creadas hace menos de 7 días\n· Próximo: distance limit, only-my-area, time-of-day"
          },
          {
            "heading": "Estado",
            "body": "UI + persistence ✓. Aplicación al query de `/v1/me/inquiries` — pendiente próximo sprint (afecta query existente)."
          }
        ]
      },
      "insignias": {
        "title": "Insignias",
        "tldr": "18 insignias en 4 categorías que reconocen logros del profesional. Públicas en el perfil, opcionalmente ocultables.",
        "sections": [
          {
            "heading": "Categorías",
            "body": "· **Tier** (5): Aprendiz → Patrón del Oficio\n· **Milestone** (5): primer trabajo, 10/50/100 trabajos, primer 5★\n· **Superlative** (3): velocista del mes, estrella del barrio, maestro del barrio\n· **Collection** (5): Perfil Maestro, multilingüe, constructor, equipo, verificado completo"
          },
          {
            "heading": "Rarity",
            "body": "common · rare · epic · legendary. Determina color del pill y peso visual."
          },
          {
            "heading": "Auto-grant",
            "body": "Las superlativos se evalúan mensualmente (cron próximo sprint). Las milestone + collection se otorgan en eventos (job completed, photo added, ruc set)."
          },
          {
            "heading": "Visibilidad",
            "body": "Por defecto públicas en el perfil. El usuario puede ocultar individualmente desde /me/?tab=game."
          }
        ]
      },
      "local-first": {
        "title": "Local-first / Offline (multi-sprint)",
        "tldr": "Páginas se renderizan offline desde cache, mutations queued, sync en reconexión, conflict resolution. Reference: Todoist.",
        "sections": [
          {
            "heading": "Vision",
            "body": "Cuando la red se cae, la app sigue funcionando: ver datos cacheados, crear/editar, queue local, sync automático al reconectar, conflict modal si hay edits paralelas."
          },
          {
            "heading": "Sub-tickets (spec §19.2)",
            "body": "10 sub-tickets: SW offline shell, IndexedDB layer, mutation queue, sync engine, conflict resolution, UI badges, background sync, optimistic UI, network detection, E2E suite (50+ scenarios)."
          },
          {
            "heading": "Estimación",
            "body": "4-6 semanas. Top priority initiative."
          }
        ]
      },
      "mis-clientes": {
        "title": "Mis clientes (Lite-CRM)",
        "tldr": "Lista de clientes recurrentes. Se agregan automáticamente al completar un trabajo. Notas editables.",
        "sections": [
          {
            "heading": "Auto-add",
            "body": "Cuando una inquiry pasa a `work_status=done` (ambos confirmaron), se crea `client_record` con: display_name, phone, barrio, job_count, last_job_at."
          },
          {
            "heading": "Notas",
            "body": "Cada record tiene un campo `notes` libre, editable por el profesional. Útil para \"le instalé el calefactor de cocina en marzo, le devuelvo en septiembre para mantenimiento\"."
          },
          {
            "heading": "Próximo: maintenance pitch",
            "body": "Para oficios con mantenimiento regular (plomería, AC), el sistema sugerirá auto-contacto al cliente N meses después de cierto tipo de trabajo."
          }
        ]
      },
      "mobile": {
        "title": "Mobile (Tauri + WebView)",
        "tldr": "iOS + Android app envolviendo el mismo código web vía Tauri 2.0 mobile. Single codebase. Sprint 7+.",
        "sections": [
          {
            "heading": "Decisión arquitectónica (spec §18)",
            "body": "NO React Native. NO Flutter. NO separate mobile app. Tauri WebView wrappea apps/site/dist directamente."
          },
          {
            "heading": "Plan",
            "body": "Sprint 7+: scaffold apps/mobile, iOS Xcode signing, Android Gradle, push notifications, share intent, biometric."
          }
        ]
      },
      "multilingue": {
        "title": "Multilingüe per-perfil",
        "tldr": "Versión en guaraní de tu bio/headline sin perder el SEO en español. Próximamente: DE, EN, RU como equal-class.",
        "sections": [
          {
            "heading": "Hoy",
            "body": "Campos `bio_gn` y `headline_gn` en el \"Perfil avanzado\". Si están llenos, aparecen en `/p/<slug>?lang=gn` con hreflang correspondiente."
          },
          {
            "heading": "Estrategia 2026-06-25 (PIVOT)",
            "body": "La estrategia comercial pivó a DE/EN/RU/ES como **idiomas equal** — apuntando a expat communities en Paraguay (alemana, inglesa, rusa) + local. Migration 0013 agregará `bio_de`/`bio_ru`/`headline_de`/`headline_ru` columns en Sprint 2."
          }
        ]
      },
      "perfil": {
        "title": "Tu perfil público",
        "tldr": "Página propia en pyaserv.com/p/<tu-slug> con foto, portada, bio, servicios con precio, galería de trabajos, reseñas, badges, horario y botón directo a WhatsApp.",
        "sections": [
          {
            "heading": "¿Qué incluye?",
            "body": "· Foto de perfil + imagen de portada (16:9)\n· Bio + servicios con rango de precio\n· Hasta 8 zonas de trabajo\n· Horario semanal\n· Galería de trabajos (hasta 24 fotos)\n· Reseñas de clientes con foto\n· Badges + tier de gamification\n· Botón sticky de WhatsApp\n· QR para tarjeta de visita\n"
          },
          {
            "heading": "URL",
            "body": "Cada profesional recibe un slug humano-friendly basado en su nombre: `pyaserv.com/p/juan-perez-019ec8`. Se genera al guardar el perfil; no se puede cambiar.\n"
          },
          {
            "heading": "SEO",
            "body": "· Title y meta description dinámicos\n· Schema.org `LocalBusiness` con aggregateRating\n· Open Graph + Twitter Card\n· Hreflang para versiones ES/EN/DE/RU\n· LCP target < 2 s en 3 G + 4× CPU\n"
          },
          {
            "heading": "Cómo editar",
            "body": "Ingresá a `/me/` → tab \"Mi perfil\" → ahí los campos básicos. Para portada / servicios / portfolio / horario / filtros / guaraní: abrir details \"Perfil avanzado\" debajo del form principal.\n"
          },
          {
            "heading": "Cómo se calcula el \"completeness\"",
            "body": "10 pasos, cada uno 10 %, comenzando con 20 % de endowed-progress (Nunes 2006). Al 100 %: insignia \"Perfil Maestro\" + 7 días de Boost gratis.\n"
          }
        ]
      },
      "recap-card": {
        "title": "Recap-card PNG (WhatsApp Status)",
        "tldr": "Generador 1080×1920 PNG semanal con métricas de la semana, listo para compartir en WhatsApp Status / Instagram Story.",
        "sections": [
          {
            "heading": "Trigger",
            "body": "Domingo 18:00 PY — auto-genera y muestra modal en /me/ si hubo actividad significativa esa semana."
          },
          {
            "heading": "Triggers adicionales",
            "body": "· Desbloqueo de insignia importante.\n· Hito numérico (50, 100 trabajos).\n· Manual \"Compartir mi semana\"."
          },
          {
            "heading": "Stack",
            "body": "Cloudflare Worker + Satori + Resvg. Pendiente bundling fix."
          }
        ]
      },
      "sifen": {
        "title": "SIFEN — factura electrónica",
        "tldr": "Generación de factura electrónica integrada con DGII en cada trabajo completado. Bloqueada por consultoría tributaria.",
        "sections": [
          {
            "heading": "Bloqueo",
            "body": "Antes de implementar necesito clarity de un contador parguayo sobre:\n· ¿Qué tipo de RUC requiere PyaServ?\n· ¿Es PyaServ emisor o sólo proveedor de infra para el profesional?\n· ¿Cómo se aplica IVA si el profesional NO tiene RUC?"
          },
          {
            "heading": "Plan",
            "body": "Sprint 5 si juicio legal positivo, sino sigue como \"soon\" hasta resolver."
          }
        ]
      },
      "this-doc": {
        "title": "Documentación + Releases",
        "tldr": "Esta página. Cada feature tiene página de detalle. Releases en /releases/ con RSS.",
        "sections": [
          {
            "heading": "Estructura",
            "body": "· `/docs/` — index con cards de todas las features.\n· `/docs/<slug>/` — página de detalle por feature (esta misma).\n· `/releases/` — notas de release ordenadas por fecha.\n· `/releases/rss.xml` — feed RSS 2.0.\n· `/components/` — Storybook lite (catálogo de componentes pure-stateless)."
          },
          {
            "heading": "Próximo",
            "body": "· Pagefind search across docs + releases.\n· Subscripción email mensual.\n· Toast on login si hay novedades desde la última visita."
          }
        ]
      },
      "tour": {
        "title": "Onboarding Tour",
        "tldr": "Tour interactivo de 7 pasos que lleva al nuevo profesional por el armado del perfil. Auto-lanza al primer ingreso a /me/ si el perfil está incompleto.",
        "sections": [
          {
            "heading": "Triggers",
            "body": "T1 \"Tu primer perfil\" — auto-lanza si: (a) primera visita a /me/, (b) no existe registro en `user_tours_completed`, (c) `profile_complete_pct < 100`."
          },
          {
            "heading": "Pasos T1",
            "body": "1. Foto · 2. Headline · 3. Bio · 4. Teléfono · 5. WhatsApp · 6. Barrio · 7. Completeness review."
          },
          {
            "heading": "Engine",
            "body": "Driver.js v1.5 (~5 KB) lazy-loaded. Spotlight + tooltip + Next/Prev/Skip. Persiste status `completed` o `skipped` en `user_tours_completed` table."
          },
          {
            "heading": "Re-launch",
            "body": "Sin recompensa XP repetida. Se puede re-lanzar manualmente desde el help menu (próximo sprint)."
          },
          {
            "heading": "Demo Mode v2",
            "body": "En vez de Driver.js, ?demo=1 activa el nuevo IntelliJ-style overlay con darken-spotlight y navegación step-by-step."
          }
        ]
      },
      "xp": {
        "title": "XP, rachas, misiones",
        "tldr": "Sistema de gamification completo: XP por acción, 5 tiers, racha diaria con freezes, misiones diarias y semanales con recompensas XP + boost.",
        "sections": [
          {
            "heading": "XP table (spec §4.4)",
            "body": "· Respuesta < 1h: +5 · Respuesta < 24h: +2 · Trabajo completado: +25 · Reseña: +30 · Reseña con foto: +50 · 5★ bonus: +20 · Foto portfolio: +5 · Compartir trabajo: +15 · Quest diaria: +10 · Quest semanal: +50 · Referido: +100"
          },
          {
            "heading": "Tiers",
            "body": "Aprendiz (0) → Oficial (100) → Maestro (500) → Maestro Mayor (2000) → Patrón del Oficio (5000). Sticky — no se baja."
          },
          {
            "heading": "Racha",
            "body": "Acción \"activa\" cualquier día (respuesta, foto, login con actividad). Auto-freeze si no hubo leads (max 3/mes). Manual pause hasta 14 días. Repair 1×/mes por 100 XP."
          },
          {
            "heading": "Quests",
            "body": "3 diarias (10 XP cada una) + 1-2 semanales (50 XP). Auto-seed cuando el usuario abre /me/?tab=game."
          }
        ]
      }
    },
    "releases": {
      "2026-06-24-spec-v1-foundation": {
        "title": "Spec v1 Foundation — schema + service areas + gamification base",
        "tldr": "Base de datos lista para todas las features de spec v1. 4 migraciones aplicadas en prod D1.",
        "sections": [
          {
            "kind": "new",
            "heading": "Migraciones",
            "body": "· **0009** — extensions a `specialist_profiles` (slug, cover, services_json, portfolio_json, schedule_json, lead_filters_json, cedula_verified, ruc_number, bio_gn, headline_gn).\n· **0010** — tablas de gamification (user_game_state, xp_events, badges_catalog con 18 seeded, user_badges, quests).\n· **0011** — user_tours_completed + slug backfill para perfiles existentes.\n· **0012** — quotes, quote_templates, client_records, release_subscriptions, user_subscriptions.\n"
          },
          {
            "kind": "new",
            "heading": "Service areas canonical",
            "body": "· 40 zonas seeded: 25 barrios de Asunción + 15 distritos de Departamento Central.\n· Tabla `service_areas` (canonical) + link `specialist_service_areas` (many-to-many, hasta 8 zonas por profesional).\n"
          },
          {
            "kind": "new",
            "heading": "Sistema de gamification base",
            "body": "· Event-sourced: cada XP grant es row inmutable en `xp_events`.\n· Materialización: `user_game_state` con projection denormalizada para lectura rápida del HUD.\n· 18 badges seeded en 4 categorías (tier · milestone · superlative · collection).\n"
          },
          {
            "kind": "new",
            "heading": "Idioma guaraní (sparse)",
            "body": "· Locale type extended a `'es' | 'en' | 'gn'`.\n· GN sparse dictionary, fallback a ES para keys faltantes.\n· Per-specialist: bio_gn, headline_gn opcionales.\n"
          }
        ]
      },
      "2026-06-25-spec-v1-features": {
        "title": "Spec v1 features live — 13 funciones + components-lib + Demo v2",
        "tldr": "Las 13 features de spec v1 en producción + components-lib pure-stateless + Demo Mode v2 con apiFetch interception.",
        "sections": [
          {
            "kind": "new",
            "heading": "Perfil público + 4 nuevos endpoints",
            "body": "· `/p/<tu-slug>` con foto, portada, bio, servicios, badges, horario, WhatsApp CTA.\n· API: `/v1/p/:slug` agrega profile + reviews + badges + tier + areas.\n· Pretty URL via CF Pages `_redirects` rewrite.\n"
          },
          {
            "kind": "new",
            "heading": "Cotizador rápido con PDF",
            "body": "· `/me/quotes/new` — editor de items, IVA toggle, jsPDF descarga client-side, share por WhatsApp.\n· Templates por oficio (próximo: bibliotecas pre-cargadas).\n"
          },
          {
            "kind": "new",
            "heading": "Gamification engine completo",
            "body": "· XP, 5 tiers (Aprendiz → Patrón), 18 badges en 4 categorías, racha diaria con freezes.\n· Misiones diarias (3) y semanales (2) con auto-seed.\n· HUD en `/me/` con XP / 🔥 racha / ⚡ tier.\n· XP grants automáticos en eventos: respuesta < 1h, job completed, review con foto.\n"
          },
          {
            "kind": "new",
            "heading": "Lite-CRM \"Mis clientes\"",
            "body": "· Auto-creación de `client_record` cuando se completa un trabajo.\n· Notas editables, contador de trabajos por cliente.\n· Próximo: recordatorios de mantenimiento N meses después.\n"
          },
          {
            "kind": "new",
            "heading": "Onboarding Tour T1",
            "body": "· Driver.js lazy-loaded, 7 pasos guiados.\n· Auto-launch al primer ingreso a `/me/` si profile_complete_pct < 100.\n· Persistencia en tabla `user_tours_completed`.\n"
          },
          {
            "kind": "new",
            "heading": "Hyperlocal SEO landings × 400",
            "body": "· `/servicios/<oficio>/<barrio>/` — 10 oficios × 40 zonas = 400 páginas auto-generadas.\n· Cada una con title/meta únicos, FAQ, CTA \"¿Sos profesional?\", live-fetch de specialists matching.\n"
          },
          {
            "kind": "new",
            "heading": "Demo Mode v2",
            "body": "· Cualquier ruta + `?demo=1` = misma app con datos canned (sin pages mock).\n· apiFetch intercepta llamadas via demoStub.\n· 10 mechanisms del Safety Charter activos: banner naranja, body tint, html[data-demo-mode], identidad logged-out, exit modal, idle timeout 10min, no data import, audit beacon.\n"
          },
          {
            "kind": "new",
            "heading": "Components library + Storybook lite",
            "body": "· `apps/site/src/components-lib/` — 19 funciones pure stateless (atoms / molecules / organisms).\n· `/components/` lista con props panel + locale switcher (debug i18n).\n· Demo Mode v2 reutiliza estas mismas funciones.\n"
          }
        ]
      },
      "2026-06-26-i18n-yaml-docs-wiki": {
        "title": "i18n YAML + 4 idiomas + docs wiki + releases full pages",
        "tldr": "Strings movidas a YAML por idioma. 4 idiomas equal — ES, EN, DE, RU. Docs es ahora wiki con sidebar. Cada release tiene página propia con detalles.",
        "sections": [
          {
            "kind": "new",
            "heading": "i18n basado en YAML",
            "body": "· Cada string vive en `apps/site/src/locales/<lang>/<ns>.yaml` — un archivo por namespace.\n· Drop un YAML, ejecutá `bun run i18n:build`, listo. Cero hardcoded strings en código nuevo.\n· **309 keys** en ES + EN con paridad obligatoria (unit test `i18n.test.ts`), 97 en DE/RU bootstrap, GN sparse.\n· Cadena de fallback: locale → EN → ES → key (last-ditch). EN canonical.\n· API `t(key)` igual que antes — sin breaking changes en callsites.\n"
          },
          {
            "kind": "new",
            "heading": "Cuatro idiomas equal — ES / EN / DE / RU",
            "body": "· Auto-detect del navegador sin sesgo al español: `de` → DE, `ru` → RU, `es` → ES, fallback EN.\n· Cuatro botones en el switcher de idioma del topbar y flying-menu (antes solo 2).\n· Aria-labels traducidas en cada idioma para el screen reader del usuario.\n· Spec §17 (multi-lang strategy) — target inicial: comunidades expat en Paraguay (alemana, inglesa, rusa) + local.\n"
          },
          {
            "kind": "new",
            "heading": "Documentación como wiki",
            "body": "· `/docs/` ahora es vista wiki con sidebar de navegación a la izquierda (no más cards).\n· Categorías: Perfil & visibilidad · Gamification · Herramientas · Sistema · Roadmap.\n· Cada feature mantiene su página propia `/docs/<slug>/`.\n· Buscador de docs viene con Pagefind en próximo release.\n"
          },
          {
            "kind": "new",
            "heading": "Releases — páginas completas",
            "body": "· `/releases/` ahora muestra cards completas con todo el contenido (no mini-cards).\n· Cada release tiene su URL propia `/releases/<slug>/` — link compartible, indexable.\n· Soporte para secciones tipadas: Nuevo / Mejorado / Arreglado / Próximamente.\n· Slots para GIFs por sección (próximamente: pipeline Playwright→ffmpeg para auto-recordings).\n"
          },
          {
            "kind": "fixed",
            "heading": "Demo banner stuck bug + tests",
            "body": "· `.ps-demo-banner { display: flex }` sobrescribía el UA `[hidden]{display:none}`, dejando el banner visible siempre.\n· Fix: `.ps-demo-banner[hidden] { display: none !important }`.\n· Suite `tests/e2e/demo-mode.common.spec.ts` — **9 scenarios × 2 viewports = 18 tests**, todos passing.\n· Sticky in-demo navigation: links a `/me/* /p/* /specialists/* /clients/*` auto-reciben `?demo=1`; los demás cortan demo.\n"
          },
          {
            "kind": "fixed",
            "heading": "Botones — focus-visible unificado",
            "body": "· Una sola regla CSS cubre `.cl-btn, .ps-lang-btn, .ps-theme-btn, .ps-tab, .gt-btn, .ps-demo-banner__exit` con `outline: 2px solid var(--ps-acc); outline-offset: 2px`.\n· Hover separado del focus-visible (antes mismo selector — accesibilidad pobre).\n"
          },
          {
            "kind": "fixed",
            "heading": "Dark theme en componentes nuevos",
            "body": "· Todos los `cl-*` (Button, Card, BadgePill, ProfileHeader, etc.) ahora usan tokens `--ps-*` de `global.css` en vez de colores hardcoded.\n· Demo banner y guided-tour respetan el tema activo.\n"
          },
          {
            "kind": "next",
            "heading": "Próximo",
            "body": "· Pagefind search en /docs/ + /releases/.\n· Email digest suscripción mensual.\n· In-app toast cuando hay release nuevo desde la última visita.\n· Recording pipeline: Playwright → ffmpeg → WebP GIFs auto-embedded en release notes.\n"
          }
        ]
      }
    }
  },
  "en": {
    "docs": {
      "perfil": {
        "title": "Your public profile",
        "tldr": "Your own page at pyaserv.com/p/<your-slug> with photo, cover, bio, services with price, portfolio gallery, reviews, badges, schedule, and a direct WhatsApp button.",
        "sections": [
          {
            "heading": "What is included",
            "body": "· Profile photo + cover image (16:9)\n· Bio + services with price range\n· Up to 8 work areas\n· Weekly schedule\n· Work gallery (up to 24 photos)\n· Customer reviews with photo\n· Badges + gamification tier\n· Sticky WhatsApp button\n· QR for business card\n"
          },
          {
            "heading": "URL",
            "body": "Each professional gets a human-friendly slug based on their name: `pyaserv.com/p/juan-perez-019ec8`. Generated when saving the profile; not changeable later.\n"
          },
          {
            "heading": "SEO",
            "body": "· Dynamic title and meta description\n· Schema.org `LocalBusiness` with aggregateRating\n· Open Graph + Twitter Card\n· Hreflang for ES/EN/DE/RU versions\n· LCP target < 2 s on 3 G + 4× CPU\n"
          },
          {
            "heading": "How to edit",
            "body": "Go to `/me/` → \"My profile\" tab → basic fields there. For cover / services / portfolio / schedule / filters / Guarani: open the \"Advanced profile\" details below the main form.\n"
          },
          {
            "heading": "How \"completeness\" is calculated",
            "body": "10 steps, 10 % each, starting at 20 % endowed-progress (Nunes 2006). At 100 %: \"Master Profile\" badge + 7 free Boost days.\n"
          }
        ]
      }
    },
    "releases": {
      "2026-06-24-spec-v1-foundation": {
        "title": "Spec v1 Foundation — schema + service areas + gamification base",
        "tldr": "Database ready for all spec v1 features. 4 migrations applied to prod D1.",
        "sections": [
          {
            "kind": "new",
            "heading": "Migrations",
            "body": "· **0009** — `specialist_profiles` extensions (slug, cover, services_json, portfolio_json, schedule_json, lead_filters_json, cedula_verified, ruc_number, bio_gn, headline_gn).\n· **0010** — gamification tables (user_game_state, xp_events, badges_catalog with 18 seeded, user_badges, quests).\n· **0011** — user_tours_completed + slug backfill for existing profiles.\n· **0012** — quotes, quote_templates, client_records, release_subscriptions, user_subscriptions.\n"
          },
          {
            "kind": "new",
            "heading": "Canonical service areas",
            "body": "· 40 areas seeded: 25 Asunción neighborhoods + 15 Departamento Central districts.\n· `service_areas` table (canonical) + `specialist_service_areas` link (many-to-many, up to 8 areas per professional).\n"
          },
          {
            "kind": "new",
            "heading": "Gamification base system",
            "body": "· Event-sourced: every XP grant is an immutable row in `xp_events`.\n· Materialization: `user_game_state` with denormalized projection for fast HUD reads.\n· 18 badges seeded in 4 categories (tier · milestone · superlative · collection).\n"
          },
          {
            "kind": "new",
            "heading": "Guarani language (sparse)",
            "body": "· Locale type extended to `'es' | 'en' | 'gn'`.\n· GN sparse dictionary, ES fallback for missing keys.\n· Per-specialist: bio_gn, headline_gn optional.\n"
          }
        ]
      },
      "2026-06-25-spec-v1-features": {
        "title": "Spec v1 features live — 13 features + components-lib + Demo v2",
        "tldr": "All 13 features of spec v1 in production + pure-stateless components-lib + Demo Mode v2 with apiFetch interception.",
        "sections": [
          {
            "kind": "new",
            "heading": "Public profile + 4 new endpoints",
            "body": "· `/p/<your-slug>` with photo, cover, bio, services, badges, schedule, WhatsApp CTA.\n· API: `/v1/p/:slug` aggregates profile + reviews + badges + tier + areas.\n· Pretty URL via CF Pages `_redirects` rewrite.\n"
          },
          {
            "kind": "new",
            "heading": "Quick quote builder with PDF",
            "body": "· `/me/quotes/new` — item editor, IVA toggle, jsPDF client-side download, WhatsApp share.\n· Per-trade templates (next: pre-loaded libraries).\n"
          },
          {
            "kind": "new",
            "heading": "Full gamification engine",
            "body": "· XP, 5 tiers (Apprentice → Patron), 18 badges in 4 categories, daily streak with freezes.\n· Daily (3) and weekly (2) quests with auto-seed.\n· HUD on `/me/` with XP / 🔥 streak / ⚡ tier.\n· Auto XP grants on events: response < 1h, job completed, review with photo.\n"
          },
          {
            "kind": "new",
            "heading": "Lite-CRM \"My clients\"",
            "body": "· Auto-create `client_record` when a job is completed.\n· Editable notes, job count per client.\n· Next: maintenance reminders N months later.\n"
          },
          {
            "kind": "new",
            "heading": "Onboarding Tour T1",
            "body": "· Driver.js lazy-loaded, 7 guided steps.\n· Auto-launch on first `/me/` visit if profile_complete_pct < 100.\n· Persisted in `user_tours_completed` table.\n"
          },
          {
            "kind": "new",
            "heading": "Hyperlocal SEO landings × 400",
            "body": "· `/servicios/<trade>/<area>/` — 10 trades × 40 areas = 400 auto-generated pages.\n· Each with unique title/meta, FAQ, \"Are you a professional?\" CTA, live-fetch of matching specialists.\n"
          },
          {
            "kind": "new",
            "heading": "Demo Mode v2",
            "body": "· Any route + `?demo=1` = same app with canned data (no mock pages).\n· apiFetch intercepts calls via demoStub.\n· 10 Safety Charter mechanisms active: orange banner, body tint, html[data-demo-mode], logged-out identity, exit modal, 10-min idle timeout, no data import, audit beacon.\n"
          },
          {
            "kind": "new",
            "heading": "Components library + Storybook lite",
            "body": "· `apps/site/src/components-lib/` — 19 pure stateless functions (atoms / molecules / organisms).\n· `/components/` list with props panel + locale switcher (i18n debugging).\n· Demo Mode v2 reuses these same functions.\n"
          }
        ]
      },
      "2026-06-26-i18n-yaml-docs-wiki": {
        "title": "i18n YAML + 4 languages + docs wiki + full release pages",
        "tldr": "Strings moved to per-locale YAML. 4 first-class languages — ES, EN, DE, RU. Docs is now a wiki with sidebar. Each release has its own URL with full details.",
        "sections": [
          {
            "kind": "new",
            "heading": "YAML-based i18n",
            "body": "· Every string lives in `apps/site/src/locales/<lang>/<ns>.yaml` — one file per namespace.\n· Drop a YAML, run `bun run i18n:build`, ship. Zero hardcoded strings in new code.\n· **309 keys** in ES + EN with mandatory parity (`i18n.test.ts` unit test), 97 in DE/RU bootstrap, GN sparse.\n· Fallback chain: locale → EN → ES → key (last-ditch). EN is canonical.\n· `t(key)` API unchanged — no breaking changes for existing callsites.\n"
          },
          {
            "kind": "new",
            "heading": "Four first-class languages — ES / EN / DE / RU",
            "body": "· Browser auto-detect without Spanish bias: `de` → DE, `ru` → RU, `es` → ES, fallback EN.\n· Four buttons in the topbar + flying-menu lang switcher (was 2).\n· Aria-labels translated per language for screen readers.\n· Spec §17 (multi-lang strategy) — initial target: expat communities in Paraguay (German, English, Russian) + local.\n"
          },
          {
            "kind": "new",
            "heading": "Documentation as wiki",
            "body": "· `/docs/` is now a wiki layout with sidebar nav on the left (no more cards).\n· Categories: Profile & visibility · Gamification · Tools · System · Roadmap.\n· Each feature keeps its own page `/docs/<slug>/`.\n· Docs search via Pagefind ships next.\n"
          },
          {
            "kind": "new",
            "heading": "Releases — full pages",
            "body": "· `/releases/` now shows full content cards (not mini-cards).\n· Each release has its own URL `/releases/<slug>/` — shareable, indexable.\n· Typed sections: New / Improved / Fixed / Coming soon.\n· Per-section GIF slots ready (Playwright→ffmpeg pipeline next).\n"
          },
          {
            "kind": "fixed",
            "heading": "Demo banner stuck bug + tests",
            "body": "· `.ps-demo-banner { display: flex }` overrode the UA `[hidden]{display:none}`, leaving the banner visible always.\n· Fix: `.ps-demo-banner[hidden] { display: none !important }`.\n· Suite `tests/e2e/demo-mode.common.spec.ts` — **9 scenarios × 2 viewports = 18 tests**, all passing.\n· Sticky in-demo nav: links to `/me/* /p/* /specialists/* /clients/*` get `?demo=1` auto-appended; others exit demo.\n"
          },
          {
            "kind": "fixed",
            "heading": "Buttons — unified focus-visible",
            "body": "· One CSS rule covers `.cl-btn, .ps-lang-btn, .ps-theme-btn, .ps-tab, .gt-btn, .ps-demo-banner__exit` with `outline: 2px solid var(--ps-acc); outline-offset: 2px`.\n· Hover separated from focus-visible (previously conflated — bad a11y).\n"
          },
          {
            "kind": "fixed",
            "heading": "Dark theme in new components",
            "body": "· All `cl-*` (Button, Card, BadgePill, ProfileHeader, etc.) now use `--ps-*` tokens from `global.css` instead of hardcoded colors.\n· Demo banner and guided-tour respect the active theme.\n"
          },
          {
            "kind": "next",
            "heading": "Coming soon",
            "body": "· Pagefind search across /docs/ + /releases/.\n· Monthly email digest subscription.\n· In-app toast when a new release ships since last visit.\n· Recording pipeline: Playwright → ffmpeg → WebP auto-embedded in release notes.\n"
          }
        ]
      }
    }
  },
  "de": {
    "docs": {},
    "releases": {
      "2026-06-24-spec-v1-foundation": {
        "title": "Spec v1 Foundation — Schema + Service Areas + Gamification-Basis",
        "tldr": "Datenbank bereit für alle Spec-v1-Features. 4 Migrationen in Prod D1 angewendet.",
        "sections": [
          {
            "kind": "new",
            "heading": "Migrationen",
            "body": "· **0009** — `specialist_profiles` Erweiterungen (slug, cover, services_json, portfolio_json, schedule_json, lead_filters_json, cedula_verified, ruc_number, bio_gn, headline_gn).\n· **0010** — Gamification-Tabellen (user_game_state, xp_events, badges_catalog mit 18 seeded, user_badges, quests).\n· **0011** — user_tours_completed + slug-Backfill für bestehende Profile.\n· **0012** — quotes, quote_templates, client_records, release_subscriptions, user_subscriptions.\n"
          },
          {
            "kind": "new",
            "heading": "Kanonische Service Areas",
            "body": "· 40 Gebiete seeded: 25 Asunción-Viertel + 15 Departamento-Central-Distrikte.\n· `service_areas` Tabelle (kanonisch) + `specialist_service_areas` Link (many-to-many, bis zu 8 Gebiete pro Profi).\n"
          },
          {
            "kind": "new",
            "heading": "Gamification-Basissystem",
            "body": "· Event-sourced: jeder XP-Grant ist eine unveränderliche Zeile in `xp_events`.\n· Materialisierung: `user_game_state` mit denormalisierter Projektion für schnelle HUD-Reads.\n· 18 Abzeichen seeded in 4 Kategorien (tier · milestone · superlative · collection).\n"
          },
          {
            "kind": "new",
            "heading": "Guarani-Sprache (sparse)",
            "body": "· Locale-Typ erweitert auf `'es' | 'en' | 'gn'`.\n· GN spärliches Wörterbuch, ES-Fallback für fehlende Keys.\n· Pro Specialist: bio_gn, headline_gn optional.\n"
          }
        ]
      },
      "2026-06-25-spec-v1-features": {
        "title": "Spec v1 Features live — 13 Funktionen + components-lib + Demo v2",
        "tldr": "Alle 13 Features von Spec v1 in Produktion + pure-stateless components-lib + Demo Mode v2 mit apiFetch-Interception.",
        "sections": [
          {
            "kind": "new",
            "heading": "Öffentliches Profil + 4 neue Endpoints",
            "body": "· `/p/<dein-slug>` mit Foto, Cover, Bio, Dienstleistungen, Abzeichen, Zeitplan, WhatsApp-CTA.\n· API: `/v1/p/:slug` aggregiert Profil + Reviews + Abzeichen + Tier + Gebiete.\n· Pretty URL via CF Pages `_redirects` Rewrite.\n"
          },
          {
            "kind": "new",
            "heading": "Schneller Kostenvoranschlag mit PDF",
            "body": "· `/me/quotes/new` — Item-Editor, IVA-Toggle, jsPDF Client-side Download, WhatsApp-Share.\n· Vorlagen pro Beruf (nächstes Mal: vorgeladene Bibliotheken).\n"
          },
          {
            "kind": "new",
            "heading": "Vollständige Gamification-Engine",
            "body": "· XP, 5 Tiers (Lehrling → Patron), 18 Abzeichen in 4 Kategorien, tägliche Serie mit Freezes.\n· Tägliche (3) und wöchentliche (2) Quests mit Auto-Seed.\n· HUD in `/me/` mit XP / 🔥 Serie / ⚡ Tier.\n· Auto-XP-Grants bei Events: Antwort < 1h, Job abgeschlossen, Bewertung mit Foto.\n"
          },
          {
            "kind": "new",
            "heading": "Lite-CRM \"Meine Kunden\"",
            "body": "· Auto-Erstellung von `client_record` bei Job-Abschluss.\n· Bearbeitbare Notizen, Job-Zähler pro Kunde.\n· Nächstes Mal: Wartungserinnerungen N Monate später.\n"
          },
          {
            "kind": "new",
            "heading": "Onboarding-Tour T1",
            "body": "· Driver.js lazy-geladen, 7 geführte Schritte.\n· Auto-Launch beim ersten `/me/`-Besuch wenn profile_complete_pct < 100.\n· Persistiert in `user_tours_completed` Tabelle.\n"
          },
          {
            "kind": "new",
            "heading": "Hyperlocal SEO-Landings × 400",
            "body": "· `/servicios/<beruf>/<gebiet>/` — 10 Berufe × 40 Gebiete = 400 auto-generierte Seiten.\n· Jede mit eindeutigem Title/Meta, FAQ, \"Bist du ein Profi?\"-CTA, Live-Fetch passender Specialists.\n"
          },
          {
            "kind": "new",
            "heading": "Demo Mode v2",
            "body": "· Jede Route + `?demo=1` = gleiche App mit Canned Data (keine Mock-Pages).\n· apiFetch fängt Aufrufe via demoStub ab.\n· 10 Safety-Charter-Mechanismen aktiv: oranges Banner, Body-Tint, html[data-demo-mode], Logged-out-Identität, Exit-Modal, 10-Min Idle-Timeout, kein Data-Import, Audit-Beacon.\n"
          },
          {
            "kind": "new",
            "heading": "Components Library + Storybook lite",
            "body": "· `apps/site/src/components-lib/` — 19 pure stateless Funktionen (Atoms / Molecules / Organisms).\n· `/components/` Liste mit Props-Panel + Locale-Switcher (i18n-Debugging).\n· Demo Mode v2 nutzt dieselben Funktionen.\n"
          }
        ]
      },
      "2026-06-26-i18n-yaml-docs-wiki": {
        "title": "i18n YAML + 4 Sprachen + Docs Wiki + vollständige Release-Seiten",
        "tldr": "Strings in per-Sprache YAML verschoben. 4 gleichrangige Sprachen — ES, EN, DE, RU. Docs ist jetzt ein Wiki mit Sidebar. Jedes Release hat seine eigene URL mit allen Details.",
        "sections": [
          {
            "kind": "new",
            "heading": "YAML-basiertes i18n",
            "body": "· Jede Zeichenkette lebt in `apps/site/src/locales/<lang>/<ns>.yaml` — eine Datei pro Namespace.\n· YAML ablegen, `bun run i18n:build` ausführen, ausliefern. Null hardcoded Strings in neuem Code.\n· **309 Keys** in ES + EN mit verpflichtender Parität (`i18n.test.ts` Unit-Test), 97 in DE/RU Bootstrap, GN spärlich.\n· Fallback-Kette: Locale → EN → ES → Key (letztes Mittel). EN kanonisch.\n· `t(key)` API unverändert — keine Breaking Changes an Callsites.\n"
          },
          {
            "kind": "new",
            "heading": "Vier gleichrangige Sprachen — ES / EN / DE / RU",
            "body": "· Browser-Autodetect ohne spanischen Bias: `de` → DE, `ru` → RU, `es` → ES, Fallback EN.\n· Vier Buttons im Topbar + flying-menu Sprachschalter (vorher 2).\n· Aria-Labels pro Sprache übersetzt für Screenreader.\n· Spec §17 (Multi-Sprach-Strategie) — initiales Ziel: Expat-Communities in Paraguay (deutsch, englisch, russisch) + lokal.\n"
          },
          {
            "kind": "new",
            "heading": "Dokumentation als Wiki",
            "body": "· `/docs/` ist jetzt eine Wiki-Ansicht mit Sidebar-Navigation links (keine Cards mehr).\n· Kategorien: Profil & Sichtbarkeit · Gamification · Werkzeuge · System · Roadmap.\n· Jedes Feature hat seine eigene Seite `/docs/<slug>/`.\n· Docs-Suche via Pagefind im nächsten Release.\n"
          },
          {
            "kind": "new",
            "heading": "Releases — vollständige Seiten",
            "body": "· `/releases/` zeigt jetzt vollständige Content-Cards (keine Mini-Cards).\n· Jedes Release hat seine eigene URL `/releases/<slug>/` — teilbar, indexierbar.\n· Typisierte Abschnitte: Neu / Verbessert / Behoben / Demnächst.\n· Pro-Sektion GIF-Slots bereit (Playwright→ffmpeg Pipeline kommt).\n"
          },
          {
            "kind": "fixed",
            "heading": "Demo-Banner stuck Bug + Tests",
            "body": "· `.ps-demo-banner { display: flex }` überschrieb das UA `[hidden]{display:none}`, das Banner blieb immer sichtbar.\n· Fix: `.ps-demo-banner[hidden] { display: none !important }`.\n· Suite `tests/e2e/demo-mode.common.spec.ts` — **9 Szenarien × 2 Viewports = 18 Tests**, alle bestanden.\n· Sticky in-demo Navigation: Links zu `/me/* /p/* /specialists/* /clients/*` bekommen `?demo=1` auto-angefügt; andere verlassen Demo.\n"
          },
          {
            "kind": "fixed",
            "heading": "Buttons — vereinheitlichtes focus-visible",
            "body": "· Eine CSS-Regel deckt `.cl-btn, .ps-lang-btn, .ps-theme-btn, .ps-tab, .gt-btn, .ps-demo-banner__exit` ab mit `outline: 2px solid var(--ps-acc); outline-offset: 2px`.\n· Hover getrennt von focus-visible (vorher gleicher Selektor — schlechte Barrierefreiheit).\n"
          },
          {
            "kind": "fixed",
            "heading": "Dark-Theme in neuen Komponenten",
            "body": "· Alle `cl-*` (Button, Card, BadgePill, ProfileHeader usw.) nutzen jetzt `--ps-*` Tokens aus `global.css` statt hardcoded Farben.\n· Demo-Banner und Guided-Tour respektieren das aktive Theme.\n"
          },
          {
            "kind": "next",
            "heading": "Demnächst",
            "body": "· Pagefind-Suche in /docs/ + /releases/.\n· Monatliches E-Mail-Digest-Abonnement.\n· In-App-Toast bei neuem Release seit letztem Besuch.\n· Recording-Pipeline: Playwright → ffmpeg → WebP auto-eingebettet in Release-Notes.\n"
          }
        ]
      }
    }
  },
  "ru": {
    "docs": {},
    "releases": {
      "2026-06-24-spec-v1-foundation": {
        "title": "Spec v1 Foundation — схема + service areas + база геймификации",
        "tldr": "База данных готова для всех фич spec v1. 4 миграции применены к prod D1.",
        "sections": [
          {
            "kind": "new",
            "heading": "Миграции",
            "body": "· **0009** — extensions `specialist_profiles` (slug, cover, services_json, portfolio_json, schedule_json, lead_filters_json, cedula_verified, ruc_number, bio_gn, headline_gn).\n· **0010** — таблицы геймификации (user_game_state, xp_events, badges_catalog с 18 seeded, user_badges, quests).\n· **0011** — user_tours_completed + slug backfill для существующих профилей.\n· **0012** — quotes, quote_templates, client_records, release_subscriptions, user_subscriptions.\n"
          },
          {
            "kind": "new",
            "heading": "Canonical service areas",
            "body": "· 40 зон seeded: 25 районов Asunción + 15 distritos Departamento Central.\n· Таблица `service_areas` (canonical) + link `specialist_service_areas` (many-to-many, до 8 зон на профи).\n"
          },
          {
            "kind": "new",
            "heading": "Базовая система геймификации",
            "body": "· Event-sourced: каждый XP grant — неизменяемая row в `xp_events`.\n· Materialization: `user_game_state` с денормализованной projection для быстрых HUD reads.\n· 18 badges seeded в 4 категориях (tier · milestone · superlative · collection).\n"
          },
          {
            "kind": "new",
            "heading": "Гуарани (sparse)",
            "body": "· Locale type расширен до `'es' | 'en' | 'gn'`.\n· GN sparse dictionary, ES fallback для отсутствующих keys.\n· Per-specialist: bio_gn, headline_gn опционально.\n"
          }
        ]
      },
      "2026-06-25-spec-v1-features": {
        "title": "Spec v1 фичи в работе — 13 функций + components-lib + Demo v2",
        "tldr": "Все 13 фич spec v1 в продакшене + pure-stateless components-lib + Demo Mode v2 с apiFetch interception.",
        "sections": [
          {
            "kind": "new",
            "heading": "Публичный профиль + 4 новых endpoint'а",
            "body": "· `/p/<твой-slug>` с фото, обложкой, био, услугами, бейджами, расписанием, WhatsApp CTA.\n· API: `/v1/p/:slug` агрегирует profile + reviews + badges + tier + areas.\n· Pretty URL через CF Pages `_redirects` rewrite.\n"
          },
          {
            "kind": "new",
            "heading": "Быстрый калькулятор смет с PDF",
            "body": "· `/me/quotes/new` — редактор позиций, IVA toggle, jsPDF client-side скачивание, шаринг через WhatsApp.\n· Шаблоны по профессиям (далее: предзагруженные библиотеки).\n"
          },
          {
            "kind": "new",
            "heading": "Полный gamification engine",
            "body": "· XP, 5 tiers (Ученик → Патрон), 18 бейджей в 4 категориях, ежедневная streak с freezes.\n· Ежедневные (3) и недельные (2) квесты с auto-seed.\n· HUD в `/me/` с XP / 🔥 streak / ⚡ tier.\n· Auto-XP grants на события: ответ < 1ч, job completed, review с фото.\n"
          },
          {
            "kind": "new",
            "heading": "Lite-CRM \"Мои клиенты\"",
            "body": "· Auto-создание `client_record` при завершении работы.\n· Редактируемые заметки, счётчик работ на клиента.\n· Далее: напоминания о сервисе через N месяцев.\n"
          },
          {
            "kind": "new",
            "heading": "Onboarding Tour T1",
            "body": "· Driver.js lazy-loaded, 7 направленных шагов.\n· Auto-запуск при первом визите `/me/` если profile_complete_pct < 100.\n· Persist в таблице `user_tours_completed`.\n"
          },
          {
            "kind": "new",
            "heading": "Hyperlocal SEO landings × 400",
            "body": "· `/servicios/<профессия>/<район>/` — 10 профессий × 40 районов = 400 авто-генерируемых страниц.\n· У каждой уникальный title/meta, FAQ, CTA «Ты профессионал?», live-fetch matching specialists.\n"
          },
          {
            "kind": "new",
            "heading": "Demo Mode v2",
            "body": "· Любая страница + `?demo=1` = то же приложение с canned data (без mock pages).\n· apiFetch перехватывает вызовы через demoStub.\n· 10 механизмов Safety Charter активны: оранжевый баннер, body tint, html[data-demo-mode], logged-out identity, exit modal, 10-min idle timeout, no data import, audit beacon.\n"
          },
          {
            "kind": "new",
            "heading": "Components library + Storybook lite",
            "body": "· `apps/site/src/components-lib/` — 19 pure stateless функций (atoms / molecules / organisms).\n· `/components/` список с props panel + locale switcher (i18n debugging).\n· Demo Mode v2 reuses те же функции.\n"
          }
        ]
      },
      "2026-06-26-i18n-yaml-docs-wiki": {
        "title": "i18n YAML + 4 языка + docs-вики + полные страницы релизов",
        "tldr": "Строки вынесены в YAML по локалям. 4 равноправных языка — ES, EN, DE, RU. Docs — теперь вики с боковым меню. У каждого релиза свой URL с полными деталями.",
        "sections": [
          {
            "kind": "new",
            "heading": "i18n на основе YAML",
            "body": "· Каждая строка живёт в `apps/site/src/locales/<lang>/<ns>.yaml` — один файл на namespace.\n· Бросаешь YAML, запускаешь `bun run i18n:build`, деплоишь. Ноль хардкоженых строк в новом коде.\n· **309 ключей** в ES + EN с обязательным паритетом (`i18n.test.ts` юнит-тест), 97 в DE/RU bootstrap, GN sparse.\n· Цепочка fallback: locale → EN → ES → key (last-ditch). EN — canonical.\n· API `t(key)` без изменений — никаких breaking changes в callsites.\n"
          },
          {
            "kind": "new",
            "heading": "Четыре равноправных языка — ES / EN / DE / RU",
            "body": "· Auto-detect браузера без испанского bias: `de` → DE, `ru` → RU, `es` → ES, fallback EN.\n· Четыре кнопки в lang-switcher топбара и flying-menu (было 2).\n· Aria-labels переведены на каждый язык для скрин-ридеров.\n· Spec §17 (multi-lang strategy) — начальный таргет: expat-сообщества в Парагвае (немецкое, английское, русское) + локальное.\n"
          },
          {
            "kind": "new",
            "heading": "Документация как вики",
            "body": "· `/docs/` — теперь вики-вид с sidebar-навигацией слева (никаких карточек).\n· Категории: Профиль и видимость · Геймификация · Инструменты · Система · Roadmap.\n· У каждой фичи своя страница `/docs/<slug>/`.\n· Поиск по docs через Pagefind — в следующем релизе.\n"
          },
          {
            "kind": "new",
            "heading": "Релизы — полные страницы",
            "body": "· `/releases/` теперь показывает полные карточки с контентом (не мини).\n· У каждого релиза свой URL `/releases/<slug>/` — шарится, индексируется.\n· Типизированные секции: Новое / Улучшено / Исправлено / Скоро.\n· Слоты для GIF на секцию (Playwright→ffmpeg pipeline скоро).\n"
          },
          {
            "kind": "fixed",
            "heading": "Demo-баннер вечный bug + тесты",
            "body": "· `.ps-demo-banner { display: flex }` перебивало UA `[hidden]{display:none}`, баннер оставался видимым всегда.\n· Fix: `.ps-demo-banner[hidden] { display: none !important }`.\n· Suite `tests/e2e/demo-mode.common.spec.ts` — **9 сценариев × 2 viewport = 18 тестов**, все прошли.\n· Sticky in-demo навигация: ссылки на `/me/* /p/* /specialists/* /clients/*` auto-получают `?demo=1`; остальные — выход из демо.\n"
          },
          {
            "kind": "fixed",
            "heading": "Кнопки — унифицированный focus-visible",
            "body": "· Одно CSS-правило покрывает `.cl-btn, .ps-lang-btn, .ps-theme-btn, .ps-tab, .gt-btn, .ps-demo-banner__exit` с `outline: 2px solid var(--ps-acc); outline-offset: 2px`.\n· Hover отделён от focus-visible (раньше тот же селектор — плохая доступность).\n"
          },
          {
            "kind": "fixed",
            "heading": "Dark theme в новых компонентах",
            "body": "· Все `cl-*` (Button, Card, BadgePill, ProfileHeader, и т.д.) теперь используют `--ps-*` токены из `global.css` вместо хардкоженых цветов.\n· Demo banner и guided-tour respect активную тему.\n"
          },
          {
            "kind": "next",
            "heading": "Скоро",
            "body": "· Pagefind search в /docs/ + /releases/.\n· Ежемесячный email-digest подписка.\n· In-app toast при новом релизе с последнего визита.\n· Recording pipeline: Playwright → ffmpeg → WebP auto-embedded в release notes.\n"
          }
        ]
      }
    }
  },
  "gn": {
    "docs": {},
    "releases": {}
  }
} as const
